/**
 * Authoritative Model Classification Dictionary for Prisma Tenant Isolation
 * Verified against AST parse of all 192 models in server/prisma/schema.prisma
 */

// Models belonging strictly to the global SaaS platform control plane (Zero tenant isolation required)
export const GLOBAL_MODELS = new Set<string>([
  "User",
  "SubscriptionPlan",
  "Coupon",
  "Addon",
  "CmsPage",
  "Permission",
  "TwoFactorOtp",
  "SystemCronJob",
  "LoginHistory",
  "StateUTMaster",
]);

// Root Tenant Entity (Has 'id' as the tenant identifier, not 'tenantId')
export const ROOT_TENANT_MODEL = "Tenant";

// Models that belong to a tenant only through a parent foreign key relationship (No direct tenant_id column)
export interface ChildModelRelation {
  parentRelation: string;
  parentModel: string;
}

export const CHILD_DEPENDENT_MODELS = new Map<string, ChildModelRelation>([
  ["SalaryStructureItem", { parentRelation: "structure", parentModel: "SalaryStructure" }],
  ["EmployeeSalaryItem", { parentRelation: "assignment", parentModel: "EmployeeSalaryAssignment" }],
  ["TaxDeclarationProof", { parentRelation: "declaration", parentModel: "EmployeeTaxDeclaration" }],
  ["FbpDeclarationItem", { parentRelation: "declaration", parentModel: "FbpDeclaration" }],
  ["OkrKeyResult", { parentRelation: "objective", parentModel: "OkrObjective" }],
  ["OkrCheckin", { parentRelation: "employee", parentModel: "Employee" }],
  ["OkrReview", { parentRelation: "cycle", parentModel: "OkrCycle" }],
  ["AssetAssignment", { parentRelation: "asset", parentModel: "Asset" }],
  ["AssetDisposalItem", { parentRelation: "batch", parentModel: "AssetDisposalBatch" }],
  ["AssetMaintenance", { parentRelation: "asset", parentModel: "Asset" }],
  ["JobCandidateInterview", { parentRelation: "candidate", parentModel: "JobCandidate" }],
  ["CourseModule", { parentRelation: "course", parentModel: "TrainingCourse" }],
  ["ExitChecklistItem", { parentRelation: "exit", parentModel: "EmployeeExit" }],
  ["HelpdeskComment", { parentRelation: "ticket", parentModel: "HelpdeskTicket" }],
  ["PlatformTicketMessage", { parentRelation: "ticket", parentModel: "PlatformSupportTicket" }],
  ["FormField", { parentRelation: "form", parentModel: "CustomForm" }],
  ["FormResponseValue", { parentRelation: "submission", parentModel: "FormSubmission" }],
  ["JournalItem", { parentRelation: "journalEntry", parentModel: "JournalEntry" }],
  ["ProductWarehouse", { parentRelation: "product", parentModel: "Product" }],
  ["SaleDetail", { parentRelation: "sale", parentModel: "Sale" }],
  ["SalePayment", { parentRelation: "sale", parentModel: "Sale" }],
  ["PurchaseDetail", { parentRelation: "purchase", parentModel: "Purchase" }],
  ["StockTransferDetail", { parentRelation: "transfer", parentModel: "StockTransfer" }],
  ["StockAdjustmentDetail", { parentRelation: "adjustment", parentModel: "StockAdjustment" }],
  ["SalesReturnDetail", { parentRelation: "salesReturn", parentModel: "SalesReturn" }],
  ["PurchaseReturnDetail", { parentRelation: "purchaseReturn", parentModel: "PurchaseReturn" }],
  ["RolePermission", { parentRelation: "role", parentModel: "WorkspaceRole" }],
  ["BankDisbursementItem", { parentRelation: "batch", parentModel: "BankDisbursementBatch" }],
  ["RecurringInvoiceItem", { parentRelation: "recurringInvoice", parentModel: "RecurringInvoice" }],
  ["MediaUsage", { parentRelation: "media", parentModel: "MediaFile" }],
  ["WorkflowStep", { parentRelation: "workflow", parentModel: "WorkflowDefinition" }],
  ["SettingSecret", { parentRelation: "setting", parentModel: "Setting" }],
  ["MeetingAttendee", { parentRelation: "meeting", parentModel: "Meeting" }],
]);

// Special Scoped Models (Scoped by scope/scopeId where scopeId is tenantId when scope=TENANT)
export const SCOPED_TENANT_MODELS = new Set<string>([
  "Setting",
  "SettingAudit",
]);

// Models with a direct tenant_id column (Primary multi-tenant entities - 147 models)
export const DIRECT_TENANT_MODELS = new Set<string>([
  "Profile",
  "UserRole",
  "Department",
  "Employee",
  "Attendance",
  "LeaveType",
  "LeaveRequest",
  "PayrollRun",
  "Payslip",
  "SalaryComponent",
  "SalaryStructure",
  "EmployeeSalaryAssignment",
  "StatutoryRule",
  "EmployeeTaxDeclaration",
  "FbpDeclaration",
  "PayrollSnapshot",
  "GenericFormTemplate",
  "TenantSubscription",
  "BillingInvoice",
  "CouponRedemption",
  "SubscriptionPolicyAudit",
  "TenantAddon",
  "OkrCycle",
  "OkrObjective",
  "AssetCategory",
  "Asset",
  "AssetRequest",
  "AssetDisposalBatch",
  "AssetActivityLog",
  "JobPosting",
  "JobCandidate",
  "JobCategory",
  "JobType",
  "JobLocation",
  "CandidateSource",
  "InterviewTypeMaster",
  "InterviewRoundMaster",
  "OfferTemplate",
  "OnboardingChecklistTemplate",
  "OnboardingCheckItem",
  "AssessmentTemplate",
  "CandidateAssessment",
  "CandidateOffer",
  "CandidateOnboarding",
  "CandidateOnboardingTask",
  "CampusCandidate",
  "EmployeeReferral",
  "ShiftDefinition",
  "ShiftRoster",
  "ShiftSwapRequest",
  "ExpenseCategory",
  "ExpenseClaim",
  "StoredDocument",
  "TrainingCourse",
  "CourseEnrollment",
  "EmployeeExit",
  "CompanyDocument",
  "HelpdeskTicket",
  "PlatformSupportTicket",
  "Announcement",
  "AnnouncementAcknowledgement",
  "CustomForm",
  "FormSubmission",
  "BiometricDevice",
  "BiometricPunchLog",
  "BiometricEmployeeMapping",
  "BiometricOfflineBuffer",
  "ChartOfAccount",
  "FiscalYear",
  "AccountingPeriod",
  "JournalEntry",
  "Contract",
  "BudgetPlan",
  "FinancialGoal",
  "ProductCategory",
  "Brand",
  "Unit",
  "TaxRate",
  "Warehouse",
  "Product",
  "Customer",
  "Supplier",
  "Sale",
  "PaymentGatewayTransaction",
  "PaymentWebhookEvent",
  "HeldOrder",
  "Purchase",
  "PurchasePayment",
  "StockTransfer",
  "StockAdjustment",
  "StockMovement",
  "ChatMessage",
  "WorkspaceRole",
  "UserRoleAssignment",
  "TenantModule",
  "CrmLead",
  "CrmProposal",
  "CrmContact",
  "CrmDeal",
  "TenantDomain",
  "WorkspaceSlugHistory",
  "WorkspaceSlugRedirect",
  "Project",
  "ProjectTask",
  "ProjectMilestone",
  "Timesheet",
  "CashRegister",
  "RegisterShift",
  "SalesReturn",
  "CreditNote",
  "PurchaseReturn",
  "DebitNote",
  "AwardType",
  "Award",
  "WarningType",
  "DisciplinaryWarning",
  "CrmCompany",
  "AutomationRule",
  "AutomationLog",
  "OvertimeRequest",
  "WfhRequest",
  "PromotionRecord",
  "ProbationRecord",
  "ProvidentFundRecord",
  "BannedIp",
  "CallHistoryRecord",
  "RecurringInvoice",
  "CustomField",
  "CustomFieldValue",
  "MarketingCampaign",
  "Branch",
  "Designation",
  "ContractType",
  "EmployeeContract",
  "Establishment",
  "StaffingClient",
  "PayrollFormula",
  "PayrollExportTemplate",
  "PayrollExecutionTrace",
  "BankDisbursementBatch",
  "StatutoryReturnFiling",
  "WorkspaceTodo",
  "WorkspaceNote",
  "CalendarEvent",
  "SubscriptionNotificationEvent",
  "MediaFile",
  "EmployeeChangeRequest",
  "ApprovalDelegation",
  "DocumentRequest",
  "CompanyProfile",
  "GSTRegistration",
  "AttendanceRegularization",
  "LeaveLedgerEntry",
  "OutboxEvent",
  "WorkflowDefinition",
  "ApprovalRequest",
  "ApprovalAction",
  "Notification",
  "NotificationTemplate",
  "AuditLog",
  "EmployeeTransfer",
  "Holiday",
  "AttendancePolicy",
  "LeavePolicy",
  "AttendanceMonthLock",
  "LeaveEncashmentRequest",
  "EmployeeLoan",
  "LoanInstallment",
  "EmployeeEvent",
  "EmployeeTrip",
  "TripExpenseItem",
  "EmployeeComplaint",
  "ComplaintCaseNote",
  "GoalTypeMaster",
  "IndicatorCategory",
  "PerformanceIndicator",
  "ReviewIndicatorRating",
  "PerformanceImprovementPlan",
  "TrainingTypeMaster",
  "TrainingSession",
  "SessionAttendance",
  "AssetDepreciationSchedule",
  "MeetingRoom",
  "MeetingTypeMaster",
  "Meeting",
  "MeetingActionItem",
  "DocumentCategory",
  "DocumentTemplate",
  "DocumentAcknowledgement",
  "GeneratedLetter",
]);

export type ModelClassification =
  | "GLOBAL"
  | "ROOT_TENANT"
  | "DIRECT_TENANT"
  | "CHILD_DEPENDENT"
  | "SCOPED_TENANT"
  | "UNKNOWN";

export function getModelClassification(model: string): ModelClassification {
  if (GLOBAL_MODELS.has(model)) return "GLOBAL";
  if (model === ROOT_TENANT_MODEL) return "ROOT_TENANT";
  if (DIRECT_TENANT_MODELS.has(model)) return "DIRECT_TENANT";
  if (CHILD_DEPENDENT_MODELS.has(model)) return "CHILD_DEPENDENT";
  if (SCOPED_TENANT_MODELS.has(model)) return "SCOPED_TENANT";
  return "UNKNOWN";
}

