SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `_prisma_migrations` ADD COLUMN `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `_prisma_migrations` ADD COLUMN `checksum` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `_prisma_migrations` ADD COLUMN `finished_at` datetime(3) DEFAULT NULL;
ALTER TABLE `_prisma_migrations` ADD COLUMN `migration_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `_prisma_migrations` ADD COLUMN `logs` text COLLATE utf8mb4_unicode_ci;
ALTER TABLE `_prisma_migrations` ADD COLUMN `rolled_back_at` datetime(3) DEFAULT NULL;
ALTER TABLE `_prisma_migrations` ADD COLUMN `started_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE `_prisma_migrations` ADD COLUMN `applied_steps_count` int unsigned NOT NULL DEFAULT '0';
ALTER TABLE `crm_companies` ADD COLUMN `employees_count` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `crm_companies` ADD COLUMN `annual_revenue` decimal(18,2) NOT NULL DEFAULT '0.00';
ALTER TABLE `crm_companies` ADD COLUMN `location` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `crm_companies` ADD COLUMN `deals_count` int NOT NULL DEFAULT '0';
ALTER TABLE `crm_companies` ADD COLUMN `notes` text COLLATE utf8mb4_unicode_ci;
ALTER TABLE `crm_contacts` ADD COLUMN `city` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `crm_contacts` ADD COLUMN `country` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT 'India';
ALTER TABLE `crm_contacts` ADD COLUMN `rating` decimal(3,1) NOT NULL DEFAULT '4.5';
ALTER TABLE `crm_contacts` ADD COLUMN `owner` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `crm_contacts` ADD COLUMN `social` json DEFAULT NULL;
ALTER TABLE `crm_contacts` ADD COLUMN `activities` json DEFAULT NULL;
ALTER TABLE `projects` ADD COLUMN `activities` json DEFAULT NULL;
ALTER TABLE `projects` ADD COLUMN `files` json DEFAULT NULL;
ALTER TABLE `projects` ADD COLUMN `notes` json DEFAULT NULL;
SET FOREIGN_KEY_CHECKS=1;
