/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as R500RouteImport } from './routes/500'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AddonsRouteImport } from './routes/addons'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomerDisplayRouteImport } from './routes/customer-display'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as OgPreviewRouteImport } from './routes/og-preview'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProductRouteImport } from './routes/product'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SuperLoginRouteImport } from './routes/super-login'
import { Route as Verify2faRouteImport } from './routes/verify-2fa'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/_app/route'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSuperRouteRouteImport } from './routes/_authenticated/super/route'
import { Route as ATagRouteImport } from './routes/a.$tag'
import { Route as AddonsSlugRouteImport } from './routes/addons.$slug'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AuthenticatedAppAccountingRouteImport } from './routes/_authenticated/_app/accounting'
import { Route as AuthenticatedAppAdjustmentsRouteImport } from './routes/_authenticated/_app/adjustments'
import { Route as AuthenticatedAppAiOcrRouteImport } from './routes/_authenticated/_app/ai-ocr'
import { Route as AuthenticatedAppAiWriterRouteImport } from './routes/_authenticated/_app/ai-writer'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated/_app/analytics'
import { Route as AuthenticatedAppAnnouncementsRouteImport } from './routes/_authenticated/_app/announcements'
import { Route as AuthenticatedAppAssetsRouteImport } from './routes/_authenticated/_app/assets'
import { Route as AuthenticatedAppAttendanceRouteImport } from './routes/_authenticated/_app/attendance'
import { Route as AuthenticatedAppBiometricRouteImport } from './routes/_authenticated/_app/biometric'
import { Route as AuthenticatedAppBiometricSyncRouteImport } from './routes/_authenticated/_app/biometric-sync'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/_app/chat'
import { Route as AuthenticatedAppCrmRouteImport } from './routes/_authenticated/_app/crm'
import { Route as AuthenticatedAppCrmDashboardRouteImport } from './routes/_authenticated/_app/crm-dashboard'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app/dashboard'
import { Route as AuthenticatedAppDocumentsRouteImport } from './routes/_authenticated/_app/documents'
import { Route as AuthenticatedAppEmployeesRouteImport } from './routes/_authenticated/_app/employees'
import { Route as AuthenticatedAppExpensesRouteImport } from './routes/_authenticated/_app/expenses'
import { Route as AuthenticatedAppFinanceDashboardRouteImport } from './routes/_authenticated/_app/finance-dashboard'
import { Route as AuthenticatedAppFormsRouteImport } from './routes/_authenticated/_app/forms'
import { Route as AuthenticatedAppGoogleWorkspaceRouteImport } from './routes/_authenticated/_app/google-workspace'
import { Route as AuthenticatedAppHelpdeskRouteImport } from './routes/_authenticated/_app/helpdesk'
import { Route as AuthenticatedAppHrmRouteImport } from './routes/_authenticated/_app/hrm'
import { Route as AuthenticatedAppIntegrationsRouteImport } from './routes/_authenticated/_app/integrations'
import { Route as AuthenticatedAppInventoryDashboardRouteImport } from './routes/_authenticated/_app/inventory-dashboard'
import { Route as AuthenticatedAppInvoicesRouteImport } from './routes/_authenticated/_app/invoices'
import { Route as AuthenticatedAppLeaveRouteImport } from './routes/_authenticated/_app/leave'
import { Route as AuthenticatedAppMarketplaceRouteImport } from './routes/_authenticated/_app/marketplace'
import { Route as AuthenticatedAppMediaRouteImport } from './routes/_authenticated/_app/media'
import { Route as AuthenticatedAppOffboardingRouteImport } from './routes/_authenticated/_app/offboarding'
import { Route as AuthenticatedAppOkrRouteImport } from './routes/_authenticated/_app/okr'
import { Route as AuthenticatedAppPayrollRouteImport } from './routes/_authenticated/_app/payroll'
import { Route as AuthenticatedAppPosRouteImport } from './routes/_authenticated/_app/pos'
import { Route as AuthenticatedAppPosDashboardRouteImport } from './routes/_authenticated/_app/pos-dashboard'
import { Route as AuthenticatedAppProcurementDashboardRouteImport } from './routes/_authenticated/_app/procurement-dashboard'
import { Route as AuthenticatedAppProductsRouteImport } from './routes/_authenticated/_app/products'
import { Route as AuthenticatedAppProjectDashboardRouteImport } from './routes/_authenticated/_app/project-dashboard'
import { Route as AuthenticatedAppProjectsRouteImport } from './routes/_authenticated/_app/projects'
import { Route as AuthenticatedAppProposalsRouteImport } from './routes/_authenticated/_app/proposals'
import { Route as AuthenticatedAppPurchasesRouteImport } from './routes/_authenticated/_app/purchases'
import { Route as AuthenticatedAppRazorpayGatewayRouteImport } from './routes/_authenticated/_app/razorpay-gateway'
import { Route as AuthenticatedAppRecruitmentRouteImport } from './routes/_authenticated/_app/recruitment'
import { Route as AuthenticatedAppSalesDashboardRouteImport } from './routes/_authenticated/_app/sales-dashboard'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/_app/settings'
import { Route as AuthenticatedAppSetupNotesRouteImport } from './routes/_authenticated/_app/setup-notes'
import { Route as AuthenticatedAppShiftsRouteImport } from './routes/_authenticated/_app/shifts'
import { Route as AuthenticatedAppShopifyRouteImport } from './routes/_authenticated/_app/shopify'
import { Route as AuthenticatedAppSubscriptionRouteImport } from './routes/_authenticated/_app/subscription'
import { Route as AuthenticatedAppSuppliersRouteImport } from './routes/_authenticated/_app/suppliers'
import { Route as AuthenticatedAppSupportRouteImport } from './routes/_authenticated/_app/support'
import { Route as AuthenticatedAppSupportDashboardRouteImport } from './routes/_authenticated/_app/support-dashboard'
import { Route as AuthenticatedAppTallyImporterRouteImport } from './routes/_authenticated/_app/tally-importer'
import { Route as AuthenticatedAppTrainingRouteImport } from './routes/_authenticated/_app/training'
import { Route as AuthenticatedAppTransfersRouteImport } from './routes/_authenticated/_app/transfers'
import { Route as AuthenticatedAppUsersRouteImport } from './routes/_authenticated/_app/users'
import { Route as AuthenticatedAppWhatsappAlertsRouteImport } from './routes/_authenticated/_app/whatsapp-alerts'
import { Route as AuthenticatedAppWorkflowsRouteImport } from './routes/_authenticated/_app/workflows'
import { Route as AuthenticatedAppWorkspaceRouteImport } from './routes/_authenticated/_app/workspace'
import { Route as AuthenticatedSuperIndexRouteImport } from './routes/_authenticated/super/index'
import { Route as AuthenticatedSuperAnalyticsRouteImport } from './routes/_authenticated/super/analytics'
import { Route as AuthenticatedSuperApiDocsRouteImport } from './routes/_authenticated/super/api-docs'
import { Route as AuthenticatedSuperBackupRouteImport } from './routes/_authenticated/super/backup'
import { Route as AuthenticatedSuperBlogsRouteImport } from './routes/_authenticated/super/blogs'
import { Route as AuthenticatedSuperCaseStudiesRouteImport } from './routes/_authenticated/super/case-studies'
import { Route as AuthenticatedSuperCmsRouteImport } from './routes/_authenticated/super/cms'
import { Route as AuthenticatedSuperEmailTemplatesRouteImport } from './routes/_authenticated/super/email-templates'
import { Route as AuthenticatedSuperLanguagesRouteImport } from './routes/_authenticated/super/languages'
import { Route as AuthenticatedSuperMarketplaceRouteImport } from './routes/_authenticated/super/marketplace'
import { Route as AuthenticatedSuperMediaRouteImport } from './routes/_authenticated/super/media'
import { Route as AuthenticatedSuperNotificationsRouteImport } from './routes/_authenticated/super/notifications'
import { Route as AuthenticatedSuperPlansRouteImport } from './routes/_authenticated/super/plans'
import { Route as AuthenticatedSuperProfileRouteImport } from './routes/_authenticated/super/profile'
import { Route as AuthenticatedSuperRolesRouteImport } from './routes/_authenticated/super/roles'
import { Route as AuthenticatedSuperSettingsRouteImport } from './routes/_authenticated/super/settings'
import { Route as AuthenticatedSuperSupportRouteImport } from './routes/_authenticated/super/support'
import { Route as AuthenticatedSuperTenantsRouteImport } from './routes/_authenticated/super/tenants'
import { Route as PortalInvoicesIdRouteImport } from './routes/portal.invoices.$id'
import { Route as PortalProposalsIdRouteImport } from './routes/portal.proposals.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AddonsRoute = AddonsRouteImport.update({
  id: '/addons',
  path: '/addons',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDisplayRoute = CustomerDisplayRouteImport.update({
  id: '/customer-display',
  path: '/customer-display',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const OgPreviewRoute = OgPreviewRouteImport.update({
  id: '/og-preview',
  path: '/og-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperLoginRoute = SuperLoginRouteImport.update({
  id: '/super-login',
  path: '/super-login',
  getParentRoute: () => rootRouteImport,
} as any)
const Verify2faRoute = Verify2faRouteImport.update({
  id: '/verify-2fa',
  path: '/verify-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperRouteRoute = AuthenticatedSuperRouteRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ATagRoute = ATagRouteImport.update({
  id: '/a/$tag',
  path: '/a/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const AddonsSlugRoute = AddonsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AddonsRoute,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppAccountingRoute =
  AuthenticatedAppAccountingRouteImport.update({
    id: '/accounting',
    path: '/accounting',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAdjustmentsRoute =
  AuthenticatedAppAdjustmentsRouteImport.update({
    id: '/adjustments',
    path: '/adjustments',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAiOcrRoute = AuthenticatedAppAiOcrRouteImport.update({
  id: '/ai-ocr',
  path: '/ai-ocr',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppAiWriterRoute =
  AuthenticatedAppAiWriterRouteImport.update({
    id: '/ai-writer',
    path: '/ai-writer',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAnnouncementsRoute =
  AuthenticatedAppAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAssetsRoute = AuthenticatedAppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppAttendanceRoute =
  AuthenticatedAppAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppBiometricRoute =
  AuthenticatedAppBiometricRouteImport.update({
    id: '/biometric',
    path: '/biometric',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppBiometricSyncRoute =
  AuthenticatedAppBiometricSyncRouteImport.update({
    id: '/biometric-sync',
    path: '/biometric-sync',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppCrmRoute = AuthenticatedAppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppCrmDashboardRoute =
  AuthenticatedAppCrmDashboardRouteImport.update({
    id: '/crm-dashboard',
    path: '/crm-dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDocumentsRoute =
  AuthenticatedAppDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppEmployeesRoute =
  AuthenticatedAppEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppExpensesRoute =
  AuthenticatedAppExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppFinanceDashboardRoute =
  AuthenticatedAppFinanceDashboardRouteImport.update({
    id: '/finance-dashboard',
    path: '/finance-dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppFormsRoute = AuthenticatedAppFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppGoogleWorkspaceRoute =
  AuthenticatedAppGoogleWorkspaceRouteImport.update({
    id: '/google-workspace',
    path: '/google-workspace',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppHelpdeskRoute =
  AuthenticatedAppHelpdeskRouteImport.update({
    id: '/helpdesk',
    path: '/helpdesk',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppHrmRoute = AuthenticatedAppHrmRouteImport.update({
  id: '/hrm',
  path: '/hrm',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppIntegrationsRoute =
  AuthenticatedAppIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppInventoryDashboardRoute =
  AuthenticatedAppInventoryDashboardRouteImport.update({
    id: '/inventory-dashboard',
    path: '/inventory-dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppInvoicesRoute =
  AuthenticatedAppInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppLeaveRoute = AuthenticatedAppLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppMarketplaceRoute =
  AuthenticatedAppMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppMediaRoute = AuthenticatedAppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppOffboardingRoute =
  AuthenticatedAppOffboardingRouteImport.update({
    id: '/offboarding',
    path: '/offboarding',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppOkrRoute = AuthenticatedAppOkrRouteImport.update({
  id: '/okr',
  path: '/okr',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppPayrollRoute = AuthenticatedAppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppPosRoute = AuthenticatedAppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppPosDashboardRoute =
  AuthenticatedAppPosDashboardRouteImport.update({
    id: '/pos-dashboard',
    path: '/pos-dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProcurementDashboardRoute =
  AuthenticatedAppProcurementDashboardRouteImport.update({
    id: '/procurement-dashboard',
    path: '/procurement-dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProductsRoute =
  AuthenticatedAppProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectDashboardRoute =
  AuthenticatedAppProjectDashboardRouteImport.update({
    id: '/project-dashboard',
    path: '/project-dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsRoute =
  AuthenticatedAppProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProposalsRoute =
  AuthenticatedAppProposalsRouteImport.update({
    id: '/proposals',
    path: '/proposals',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPurchasesRoute =
  AuthenticatedAppPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppRazorpayGatewayRoute =
  AuthenticatedAppRazorpayGatewayRouteImport.update({
    id: '/razorpay-gateway',
    path: '/razorpay-gateway',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppRecruitmentRoute =
  AuthenticatedAppRecruitmentRouteImport.update({
    id: '/recruitment',
    path: '/recruitment',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSalesDashboardRoute =
  AuthenticatedAppSalesDashboardRouteImport.update({
    id: '/sales-dashboard',
    path: '/sales-dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSetupNotesRoute =
  AuthenticatedAppSetupNotesRouteImport.update({
    id: '/setup-notes',
    path: '/setup-notes',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppShiftsRoute = AuthenticatedAppShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppShopifyRoute = AuthenticatedAppShopifyRouteImport.update({
  id: '/shopify',
  path: '/shopify',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSubscriptionRoute =
  AuthenticatedAppSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSuppliersRoute =
  AuthenticatedAppSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSupportRoute = AuthenticatedAppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSupportDashboardRoute =
  AuthenticatedAppSupportDashboardRouteImport.update({
    id: '/support-dashboard',
    path: '/support-dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppTallyImporterRoute =
  AuthenticatedAppTallyImporterRouteImport.update({
    id: '/tally-importer',
    path: '/tally-importer',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppTrainingRoute =
  AuthenticatedAppTrainingRouteImport.update({
    id: '/training',
    path: '/training',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppTransfersRoute =
  AuthenticatedAppTransfersRouteImport.update({
    id: '/transfers',
    path: '/transfers',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppUsersRoute = AuthenticatedAppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppWhatsappAlertsRoute =
  AuthenticatedAppWhatsappAlertsRouteImport.update({
    id: '/whatsapp-alerts',
    path: '/whatsapp-alerts',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppWorkflowsRoute =
  AuthenticatedAppWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppWorkspaceRoute =
  AuthenticatedAppWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedSuperIndexRoute = AuthenticatedSuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSuperRouteRoute,
} as any)
const AuthenticatedSuperAnalyticsRoute =
  AuthenticatedSuperAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const AuthenticatedSuperApiDocsRoute =
  AuthenticatedSuperApiDocsRouteImport.update({
    id: '/api-docs',
    path: '/api-docs',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const AuthenticatedSuperBackupRoute =
  AuthenticatedSuperBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const AuthenticatedSuperBlogsRoute = AuthenticatedSuperBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AuthenticatedSuperRouteRoute,
} as any)
const AuthenticatedSuperCaseStudiesRoute =
  AuthenticatedSuperCaseStudiesRouteImport.update({
    id: '/case-studies',
    path: '/case-studies',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const AuthenticatedSuperCmsRoute = AuthenticatedSuperCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AuthenticatedSuperRouteRoute,
} as any)
const AuthenticatedSuperEmailTemplatesRoute =
  AuthenticatedSuperEmailTemplatesRouteImport.update({
    id: '/email-templates',
    path: '/email-templates',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const AuthenticatedSuperLanguagesRoute =
  AuthenticatedSuperLanguagesRouteImport.update({
    id: '/languages',
    path: '/languages',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const AuthenticatedSuperMarketplaceRoute =
  AuthenticatedSuperMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const AuthenticatedSuperMediaRoute = AuthenticatedSuperMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedSuperRouteRoute,
} as any)
const AuthenticatedSuperNotificationsRoute =
  AuthenticatedSuperNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const AuthenticatedSuperPlansRoute = AuthenticatedSuperPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedSuperRouteRoute,
} as any)
const AuthenticatedSuperProfileRoute =
  AuthenticatedSuperProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const AuthenticatedSuperRolesRoute = AuthenticatedSuperRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedSuperRouteRoute,
} as any)
const AuthenticatedSuperSettingsRoute =
  AuthenticatedSuperSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const AuthenticatedSuperSupportRoute =
  AuthenticatedSuperSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const AuthenticatedSuperTenantsRoute =
  AuthenticatedSuperTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const PortalInvoicesIdRoute = PortalInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProposalsIdRoute = PortalProposalsIdRouteImport.update({
  id: '/proposals/$id',
  path: '/proposals/$id',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/about': typeof AboutRoute
  '/addons': typeof AddonsRouteWithChildren
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/customer-display': typeof CustomerDisplayRoute
  '/maintenance': typeof MaintenanceRoute
  '/og-preview': typeof OgPreviewRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRoute
  '/store': typeof StoreRoute
  '/super-login': typeof SuperLoginRoute
  '/verify-2fa': typeof Verify2faRoute
  '/super': typeof AuthenticatedSuperRouteRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/a/$tag': typeof ATagRoute
  '/addons/$slug': typeof AddonsSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/accounting': typeof AuthenticatedAppAccountingRoute
  '/adjustments': typeof AuthenticatedAppAdjustmentsRoute
  '/ai-ocr': typeof AuthenticatedAppAiOcrRoute
  '/ai-writer': typeof AuthenticatedAppAiWriterRoute
  '/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/announcements': typeof AuthenticatedAppAnnouncementsRoute
  '/assets': typeof AuthenticatedAppAssetsRoute
  '/attendance': typeof AuthenticatedAppAttendanceRoute
  '/biometric': typeof AuthenticatedAppBiometricRoute
  '/biometric-sync': typeof AuthenticatedAppBiometricSyncRoute
  '/chat': typeof AuthenticatedAppChatRoute
  '/crm': typeof AuthenticatedAppCrmRoute
  '/crm-dashboard': typeof AuthenticatedAppCrmDashboardRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/documents': typeof AuthenticatedAppDocumentsRoute
  '/employees': typeof AuthenticatedAppEmployeesRoute
  '/expenses': typeof AuthenticatedAppExpensesRoute
  '/finance-dashboard': typeof AuthenticatedAppFinanceDashboardRoute
  '/forms': typeof AuthenticatedAppFormsRoute
  '/google-workspace': typeof AuthenticatedAppGoogleWorkspaceRoute
  '/helpdesk': typeof AuthenticatedAppHelpdeskRoute
  '/hrm': typeof AuthenticatedAppHrmRoute
  '/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/inventory-dashboard': typeof AuthenticatedAppInventoryDashboardRoute
  '/invoices': typeof AuthenticatedAppInvoicesRoute
  '/leave': typeof AuthenticatedAppLeaveRoute
  '/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/media': typeof AuthenticatedAppMediaRoute
  '/offboarding': typeof AuthenticatedAppOffboardingRoute
  '/okr': typeof AuthenticatedAppOkrRoute
  '/payroll': typeof AuthenticatedAppPayrollRoute
  '/pos': typeof AuthenticatedAppPosRoute
  '/pos-dashboard': typeof AuthenticatedAppPosDashboardRoute
  '/procurement-dashboard': typeof AuthenticatedAppProcurementDashboardRoute
  '/products': typeof AuthenticatedAppProductsRoute
  '/project-dashboard': typeof AuthenticatedAppProjectDashboardRoute
  '/projects': typeof AuthenticatedAppProjectsRoute
  '/proposals': typeof AuthenticatedAppProposalsRoute
  '/purchases': typeof AuthenticatedAppPurchasesRoute
  '/razorpay-gateway': typeof AuthenticatedAppRazorpayGatewayRoute
  '/recruitment': typeof AuthenticatedAppRecruitmentRoute
  '/sales-dashboard': typeof AuthenticatedAppSalesDashboardRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/setup-notes': typeof AuthenticatedAppSetupNotesRoute
  '/shifts': typeof AuthenticatedAppShiftsRoute
  '/shopify': typeof AuthenticatedAppShopifyRoute
  '/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/suppliers': typeof AuthenticatedAppSuppliersRoute
  '/support': typeof AuthenticatedAppSupportRoute
  '/support-dashboard': typeof AuthenticatedAppSupportDashboardRoute
  '/tally-importer': typeof AuthenticatedAppTallyImporterRoute
  '/training': typeof AuthenticatedAppTrainingRoute
  '/transfers': typeof AuthenticatedAppTransfersRoute
  '/users': typeof AuthenticatedAppUsersRoute
  '/whatsapp-alerts': typeof AuthenticatedAppWhatsappAlertsRoute
  '/workflows': typeof AuthenticatedAppWorkflowsRoute
  '/workspace': typeof AuthenticatedAppWorkspaceRoute
  '/super/analytics': typeof AuthenticatedSuperAnalyticsRoute
  '/super/api-docs': typeof AuthenticatedSuperApiDocsRoute
  '/super/backup': typeof AuthenticatedSuperBackupRoute
  '/super/blogs': typeof AuthenticatedSuperBlogsRoute
  '/super/case-studies': typeof AuthenticatedSuperCaseStudiesRoute
  '/super/cms': typeof AuthenticatedSuperCmsRoute
  '/super/email-templates': typeof AuthenticatedSuperEmailTemplatesRoute
  '/super/languages': typeof AuthenticatedSuperLanguagesRoute
  '/super/marketplace': typeof AuthenticatedSuperMarketplaceRoute
  '/super/media': typeof AuthenticatedSuperMediaRoute
  '/super/notifications': typeof AuthenticatedSuperNotificationsRoute
  '/super/plans': typeof AuthenticatedSuperPlansRoute
  '/super/profile': typeof AuthenticatedSuperProfileRoute
  '/super/roles': typeof AuthenticatedSuperRolesRoute
  '/super/settings': typeof AuthenticatedSuperSettingsRoute
  '/super/support': typeof AuthenticatedSuperSupportRoute
  '/super/tenants': typeof AuthenticatedSuperTenantsRoute
  '/portal/invoices/$id': typeof PortalInvoicesIdRoute
  '/portal/proposals/$id': typeof PortalProposalsIdRoute
  '/super/': typeof AuthenticatedSuperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/about': typeof AboutRoute
  '/addons': typeof AddonsRouteWithChildren
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/customer-display': typeof CustomerDisplayRoute
  '/maintenance': typeof MaintenanceRoute
  '/og-preview': typeof OgPreviewRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRoute
  '/store': typeof StoreRoute
  '/super-login': typeof SuperLoginRoute
  '/verify-2fa': typeof Verify2faRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/a/$tag': typeof ATagRoute
  '/addons/$slug': typeof AddonsSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/accounting': typeof AuthenticatedAppAccountingRoute
  '/adjustments': typeof AuthenticatedAppAdjustmentsRoute
  '/ai-ocr': typeof AuthenticatedAppAiOcrRoute
  '/ai-writer': typeof AuthenticatedAppAiWriterRoute
  '/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/announcements': typeof AuthenticatedAppAnnouncementsRoute
  '/assets': typeof AuthenticatedAppAssetsRoute
  '/attendance': typeof AuthenticatedAppAttendanceRoute
  '/biometric': typeof AuthenticatedAppBiometricRoute
  '/biometric-sync': typeof AuthenticatedAppBiometricSyncRoute
  '/chat': typeof AuthenticatedAppChatRoute
  '/crm': typeof AuthenticatedAppCrmRoute
  '/crm-dashboard': typeof AuthenticatedAppCrmDashboardRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/documents': typeof AuthenticatedAppDocumentsRoute
  '/employees': typeof AuthenticatedAppEmployeesRoute
  '/expenses': typeof AuthenticatedAppExpensesRoute
  '/finance-dashboard': typeof AuthenticatedAppFinanceDashboardRoute
  '/forms': typeof AuthenticatedAppFormsRoute
  '/google-workspace': typeof AuthenticatedAppGoogleWorkspaceRoute
  '/helpdesk': typeof AuthenticatedAppHelpdeskRoute
  '/hrm': typeof AuthenticatedAppHrmRoute
  '/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/inventory-dashboard': typeof AuthenticatedAppInventoryDashboardRoute
  '/invoices': typeof AuthenticatedAppInvoicesRoute
  '/leave': typeof AuthenticatedAppLeaveRoute
  '/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/media': typeof AuthenticatedAppMediaRoute
  '/offboarding': typeof AuthenticatedAppOffboardingRoute
  '/okr': typeof AuthenticatedAppOkrRoute
  '/payroll': typeof AuthenticatedAppPayrollRoute
  '/pos': typeof AuthenticatedAppPosRoute
  '/pos-dashboard': typeof AuthenticatedAppPosDashboardRoute
  '/procurement-dashboard': typeof AuthenticatedAppProcurementDashboardRoute
  '/products': typeof AuthenticatedAppProductsRoute
  '/project-dashboard': typeof AuthenticatedAppProjectDashboardRoute
  '/projects': typeof AuthenticatedAppProjectsRoute
  '/proposals': typeof AuthenticatedAppProposalsRoute
  '/purchases': typeof AuthenticatedAppPurchasesRoute
  '/razorpay-gateway': typeof AuthenticatedAppRazorpayGatewayRoute
  '/recruitment': typeof AuthenticatedAppRecruitmentRoute
  '/sales-dashboard': typeof AuthenticatedAppSalesDashboardRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/setup-notes': typeof AuthenticatedAppSetupNotesRoute
  '/shifts': typeof AuthenticatedAppShiftsRoute
  '/shopify': typeof AuthenticatedAppShopifyRoute
  '/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/suppliers': typeof AuthenticatedAppSuppliersRoute
  '/support': typeof AuthenticatedAppSupportRoute
  '/support-dashboard': typeof AuthenticatedAppSupportDashboardRoute
  '/tally-importer': typeof AuthenticatedAppTallyImporterRoute
  '/training': typeof AuthenticatedAppTrainingRoute
  '/transfers': typeof AuthenticatedAppTransfersRoute
  '/users': typeof AuthenticatedAppUsersRoute
  '/whatsapp-alerts': typeof AuthenticatedAppWhatsappAlertsRoute
  '/workflows': typeof AuthenticatedAppWorkflowsRoute
  '/workspace': typeof AuthenticatedAppWorkspaceRoute
  '/super/analytics': typeof AuthenticatedSuperAnalyticsRoute
  '/super/api-docs': typeof AuthenticatedSuperApiDocsRoute
  '/super/backup': typeof AuthenticatedSuperBackupRoute
  '/super/blogs': typeof AuthenticatedSuperBlogsRoute
  '/super/case-studies': typeof AuthenticatedSuperCaseStudiesRoute
  '/super/cms': typeof AuthenticatedSuperCmsRoute
  '/super/email-templates': typeof AuthenticatedSuperEmailTemplatesRoute
  '/super/languages': typeof AuthenticatedSuperLanguagesRoute
  '/super/marketplace': typeof AuthenticatedSuperMarketplaceRoute
  '/super/media': typeof AuthenticatedSuperMediaRoute
  '/super/notifications': typeof AuthenticatedSuperNotificationsRoute
  '/super/plans': typeof AuthenticatedSuperPlansRoute
  '/super/profile': typeof AuthenticatedSuperProfileRoute
  '/super/roles': typeof AuthenticatedSuperRolesRoute
  '/super/settings': typeof AuthenticatedSuperSettingsRoute
  '/super/support': typeof AuthenticatedSuperSupportRoute
  '/super/tenants': typeof AuthenticatedSuperTenantsRoute
  '/portal/invoices/$id': typeof PortalInvoicesIdRoute
  '/portal/proposals/$id': typeof PortalProposalsIdRoute
  '/super': typeof AuthenticatedSuperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/about': typeof AboutRoute
  '/addons': typeof AddonsRouteWithChildren
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/customer-display': typeof CustomerDisplayRoute
  '/maintenance': typeof MaintenanceRoute
  '/og-preview': typeof OgPreviewRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRoute
  '/store': typeof StoreRoute
  '/super-login': typeof SuperLoginRoute
  '/verify-2fa': typeof Verify2faRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/super': typeof AuthenticatedSuperRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/a/$tag': typeof ATagRoute
  '/addons/$slug': typeof AddonsSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/_authenticated/_app/accounting': typeof AuthenticatedAppAccountingRoute
  '/_authenticated/_app/adjustments': typeof AuthenticatedAppAdjustmentsRoute
  '/_authenticated/_app/ai-ocr': typeof AuthenticatedAppAiOcrRoute
  '/_authenticated/_app/ai-writer': typeof AuthenticatedAppAiWriterRoute
  '/_authenticated/_app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/_app/announcements': typeof AuthenticatedAppAnnouncementsRoute
  '/_authenticated/_app/assets': typeof AuthenticatedAppAssetsRoute
  '/_authenticated/_app/attendance': typeof AuthenticatedAppAttendanceRoute
  '/_authenticated/_app/biometric': typeof AuthenticatedAppBiometricRoute
  '/_authenticated/_app/biometric-sync': typeof AuthenticatedAppBiometricSyncRoute
  '/_authenticated/_app/chat': typeof AuthenticatedAppChatRoute
  '/_authenticated/_app/crm': typeof AuthenticatedAppCrmRoute
  '/_authenticated/_app/crm-dashboard': typeof AuthenticatedAppCrmDashboardRoute
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/documents': typeof AuthenticatedAppDocumentsRoute
  '/_authenticated/_app/employees': typeof AuthenticatedAppEmployeesRoute
  '/_authenticated/_app/expenses': typeof AuthenticatedAppExpensesRoute
  '/_authenticated/_app/finance-dashboard': typeof AuthenticatedAppFinanceDashboardRoute
  '/_authenticated/_app/forms': typeof AuthenticatedAppFormsRoute
  '/_authenticated/_app/google-workspace': typeof AuthenticatedAppGoogleWorkspaceRoute
  '/_authenticated/_app/helpdesk': typeof AuthenticatedAppHelpdeskRoute
  '/_authenticated/_app/hrm': typeof AuthenticatedAppHrmRoute
  '/_authenticated/_app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/_authenticated/_app/inventory-dashboard': typeof AuthenticatedAppInventoryDashboardRoute
  '/_authenticated/_app/invoices': typeof AuthenticatedAppInvoicesRoute
  '/_authenticated/_app/leave': typeof AuthenticatedAppLeaveRoute
  '/_authenticated/_app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/_authenticated/_app/media': typeof AuthenticatedAppMediaRoute
  '/_authenticated/_app/offboarding': typeof AuthenticatedAppOffboardingRoute
  '/_authenticated/_app/okr': typeof AuthenticatedAppOkrRoute
  '/_authenticated/_app/payroll': typeof AuthenticatedAppPayrollRoute
  '/_authenticated/_app/pos': typeof AuthenticatedAppPosRoute
  '/_authenticated/_app/pos-dashboard': typeof AuthenticatedAppPosDashboardRoute
  '/_authenticated/_app/procurement-dashboard': typeof AuthenticatedAppProcurementDashboardRoute
  '/_authenticated/_app/products': typeof AuthenticatedAppProductsRoute
  '/_authenticated/_app/project-dashboard': typeof AuthenticatedAppProjectDashboardRoute
  '/_authenticated/_app/projects': typeof AuthenticatedAppProjectsRoute
  '/_authenticated/_app/proposals': typeof AuthenticatedAppProposalsRoute
  '/_authenticated/_app/purchases': typeof AuthenticatedAppPurchasesRoute
  '/_authenticated/_app/razorpay-gateway': typeof AuthenticatedAppRazorpayGatewayRoute
  '/_authenticated/_app/recruitment': typeof AuthenticatedAppRecruitmentRoute
  '/_authenticated/_app/sales-dashboard': typeof AuthenticatedAppSalesDashboardRoute
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/_app/setup-notes': typeof AuthenticatedAppSetupNotesRoute
  '/_authenticated/_app/shifts': typeof AuthenticatedAppShiftsRoute
  '/_authenticated/_app/shopify': typeof AuthenticatedAppShopifyRoute
  '/_authenticated/_app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/_authenticated/_app/suppliers': typeof AuthenticatedAppSuppliersRoute
  '/_authenticated/_app/support': typeof AuthenticatedAppSupportRoute
  '/_authenticated/_app/support-dashboard': typeof AuthenticatedAppSupportDashboardRoute
  '/_authenticated/_app/tally-importer': typeof AuthenticatedAppTallyImporterRoute
  '/_authenticated/_app/training': typeof AuthenticatedAppTrainingRoute
  '/_authenticated/_app/transfers': typeof AuthenticatedAppTransfersRoute
  '/_authenticated/_app/users': typeof AuthenticatedAppUsersRoute
  '/_authenticated/_app/whatsapp-alerts': typeof AuthenticatedAppWhatsappAlertsRoute
  '/_authenticated/_app/workflows': typeof AuthenticatedAppWorkflowsRoute
  '/_authenticated/_app/workspace': typeof AuthenticatedAppWorkspaceRoute
  '/_authenticated/super/analytics': typeof AuthenticatedSuperAnalyticsRoute
  '/_authenticated/super/api-docs': typeof AuthenticatedSuperApiDocsRoute
  '/_authenticated/super/backup': typeof AuthenticatedSuperBackupRoute
  '/_authenticated/super/blogs': typeof AuthenticatedSuperBlogsRoute
  '/_authenticated/super/case-studies': typeof AuthenticatedSuperCaseStudiesRoute
  '/_authenticated/super/cms': typeof AuthenticatedSuperCmsRoute
  '/_authenticated/super/email-templates': typeof AuthenticatedSuperEmailTemplatesRoute
  '/_authenticated/super/languages': typeof AuthenticatedSuperLanguagesRoute
  '/_authenticated/super/marketplace': typeof AuthenticatedSuperMarketplaceRoute
  '/_authenticated/super/media': typeof AuthenticatedSuperMediaRoute
  '/_authenticated/super/notifications': typeof AuthenticatedSuperNotificationsRoute
  '/_authenticated/super/plans': typeof AuthenticatedSuperPlansRoute
  '/_authenticated/super/profile': typeof AuthenticatedSuperProfileRoute
  '/_authenticated/super/roles': typeof AuthenticatedSuperRolesRoute
  '/_authenticated/super/settings': typeof AuthenticatedSuperSettingsRoute
  '/_authenticated/super/support': typeof AuthenticatedSuperSupportRoute
  '/_authenticated/super/tenants': typeof AuthenticatedSuperTenantsRoute
  '/portal/invoices/$id': typeof PortalInvoicesIdRoute
  '/portal/proposals/$id': typeof PortalProposalsIdRoute
  '/_authenticated/super/': typeof AuthenticatedSuperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/500'
    | '/about'
    | '/addons'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/customer-display'
    | '/maintenance'
    | '/og-preview'
    | '/portal'
    | '/pricing'
    | '/product'
    | '/resources'
    | '/solutions'
    | '/store'
    | '/super-login'
    | '/verify-2fa'
    | '/super'
    | '/onboarding'
    | '/a/$tag'
    | '/addons/$slug'
    | '/legal/$slug'
    | '/p/$slug'
    | '/accounting'
    | '/adjustments'
    | '/ai-ocr'
    | '/ai-writer'
    | '/analytics'
    | '/announcements'
    | '/assets'
    | '/attendance'
    | '/biometric'
    | '/biometric-sync'
    | '/chat'
    | '/crm'
    | '/crm-dashboard'
    | '/dashboard'
    | '/documents'
    | '/employees'
    | '/expenses'
    | '/finance-dashboard'
    | '/forms'
    | '/google-workspace'
    | '/helpdesk'
    | '/hrm'
    | '/integrations'
    | '/inventory-dashboard'
    | '/invoices'
    | '/leave'
    | '/marketplace'
    | '/media'
    | '/offboarding'
    | '/okr'
    | '/payroll'
    | '/pos'
    | '/pos-dashboard'
    | '/procurement-dashboard'
    | '/products'
    | '/project-dashboard'
    | '/projects'
    | '/proposals'
    | '/purchases'
    | '/razorpay-gateway'
    | '/recruitment'
    | '/sales-dashboard'
    | '/settings'
    | '/setup-notes'
    | '/shifts'
    | '/shopify'
    | '/subscription'
    | '/suppliers'
    | '/support'
    | '/support-dashboard'
    | '/tally-importer'
    | '/training'
    | '/transfers'
    | '/users'
    | '/whatsapp-alerts'
    | '/workflows'
    | '/workspace'
    | '/super/analytics'
    | '/super/api-docs'
    | '/super/backup'
    | '/super/blogs'
    | '/super/case-studies'
    | '/super/cms'
    | '/super/email-templates'
    | '/super/languages'
    | '/super/marketplace'
    | '/super/media'
    | '/super/notifications'
    | '/super/plans'
    | '/super/profile'
    | '/super/roles'
    | '/super/settings'
    | '/super/support'
    | '/super/tenants'
    | '/portal/invoices/$id'
    | '/portal/proposals/$id'
    | '/super/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/500'
    | '/about'
    | '/addons'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/customer-display'
    | '/maintenance'
    | '/og-preview'
    | '/portal'
    | '/pricing'
    | '/product'
    | '/resources'
    | '/solutions'
    | '/store'
    | '/super-login'
    | '/verify-2fa'
    | '/onboarding'
    | '/a/$tag'
    | '/addons/$slug'
    | '/legal/$slug'
    | '/p/$slug'
    | '/accounting'
    | '/adjustments'
    | '/ai-ocr'
    | '/ai-writer'
    | '/analytics'
    | '/announcements'
    | '/assets'
    | '/attendance'
    | '/biometric'
    | '/biometric-sync'
    | '/chat'
    | '/crm'
    | '/crm-dashboard'
    | '/dashboard'
    | '/documents'
    | '/employees'
    | '/expenses'
    | '/finance-dashboard'
    | '/forms'
    | '/google-workspace'
    | '/helpdesk'
    | '/hrm'
    | '/integrations'
    | '/inventory-dashboard'
    | '/invoices'
    | '/leave'
    | '/marketplace'
    | '/media'
    | '/offboarding'
    | '/okr'
    | '/payroll'
    | '/pos'
    | '/pos-dashboard'
    | '/procurement-dashboard'
    | '/products'
    | '/project-dashboard'
    | '/projects'
    | '/proposals'
    | '/purchases'
    | '/razorpay-gateway'
    | '/recruitment'
    | '/sales-dashboard'
    | '/settings'
    | '/setup-notes'
    | '/shifts'
    | '/shopify'
    | '/subscription'
    | '/suppliers'
    | '/support'
    | '/support-dashboard'
    | '/tally-importer'
    | '/training'
    | '/transfers'
    | '/users'
    | '/whatsapp-alerts'
    | '/workflows'
    | '/workspace'
    | '/super/analytics'
    | '/super/api-docs'
    | '/super/backup'
    | '/super/blogs'
    | '/super/case-studies'
    | '/super/cms'
    | '/super/email-templates'
    | '/super/languages'
    | '/super/marketplace'
    | '/super/media'
    | '/super/notifications'
    | '/super/plans'
    | '/super/profile'
    | '/super/roles'
    | '/super/settings'
    | '/super/support'
    | '/super/tenants'
    | '/portal/invoices/$id'
    | '/portal/proposals/$id'
    | '/super'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/404'
    | '/500'
    | '/about'
    | '/addons'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/customer-display'
    | '/maintenance'
    | '/og-preview'
    | '/portal'
    | '/pricing'
    | '/product'
    | '/resources'
    | '/solutions'
    | '/store'
    | '/super-login'
    | '/verify-2fa'
    | '/_authenticated/_app'
    | '/_authenticated/super'
    | '/_authenticated/onboarding'
    | '/a/$tag'
    | '/addons/$slug'
    | '/legal/$slug'
    | '/p/$slug'
    | '/_authenticated/_app/accounting'
    | '/_authenticated/_app/adjustments'
    | '/_authenticated/_app/ai-ocr'
    | '/_authenticated/_app/ai-writer'
    | '/_authenticated/_app/analytics'
    | '/_authenticated/_app/announcements'
    | '/_authenticated/_app/assets'
    | '/_authenticated/_app/attendance'
    | '/_authenticated/_app/biometric'
    | '/_authenticated/_app/biometric-sync'
    | '/_authenticated/_app/chat'
    | '/_authenticated/_app/crm'
    | '/_authenticated/_app/crm-dashboard'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/documents'
    | '/_authenticated/_app/employees'
    | '/_authenticated/_app/expenses'
    | '/_authenticated/_app/finance-dashboard'
    | '/_authenticated/_app/forms'
    | '/_authenticated/_app/google-workspace'
    | '/_authenticated/_app/helpdesk'
    | '/_authenticated/_app/hrm'
    | '/_authenticated/_app/integrations'
    | '/_authenticated/_app/inventory-dashboard'
    | '/_authenticated/_app/invoices'
    | '/_authenticated/_app/leave'
    | '/_authenticated/_app/marketplace'
    | '/_authenticated/_app/media'
    | '/_authenticated/_app/offboarding'
    | '/_authenticated/_app/okr'
    | '/_authenticated/_app/payroll'
    | '/_authenticated/_app/pos'
    | '/_authenticated/_app/pos-dashboard'
    | '/_authenticated/_app/procurement-dashboard'
    | '/_authenticated/_app/products'
    | '/_authenticated/_app/project-dashboard'
    | '/_authenticated/_app/projects'
    | '/_authenticated/_app/proposals'
    | '/_authenticated/_app/purchases'
    | '/_authenticated/_app/razorpay-gateway'
    | '/_authenticated/_app/recruitment'
    | '/_authenticated/_app/sales-dashboard'
    | '/_authenticated/_app/settings'
    | '/_authenticated/_app/setup-notes'
    | '/_authenticated/_app/shifts'
    | '/_authenticated/_app/shopify'
    | '/_authenticated/_app/subscription'
    | '/_authenticated/_app/suppliers'
    | '/_authenticated/_app/support'
    | '/_authenticated/_app/support-dashboard'
    | '/_authenticated/_app/tally-importer'
    | '/_authenticated/_app/training'
    | '/_authenticated/_app/transfers'
    | '/_authenticated/_app/users'
    | '/_authenticated/_app/whatsapp-alerts'
    | '/_authenticated/_app/workflows'
    | '/_authenticated/_app/workspace'
    | '/_authenticated/super/analytics'
    | '/_authenticated/super/api-docs'
    | '/_authenticated/super/backup'
    | '/_authenticated/super/blogs'
    | '/_authenticated/super/case-studies'
    | '/_authenticated/super/cms'
    | '/_authenticated/super/email-templates'
    | '/_authenticated/super/languages'
    | '/_authenticated/super/marketplace'
    | '/_authenticated/super/media'
    | '/_authenticated/super/notifications'
    | '/_authenticated/super/plans'
    | '/_authenticated/super/profile'
    | '/_authenticated/super/roles'
    | '/_authenticated/super/settings'
    | '/_authenticated/super/support'
    | '/_authenticated/super/tenants'
    | '/portal/invoices/$id'
    | '/portal/proposals/$id'
    | '/_authenticated/super/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  R404Route: typeof R404Route
  R500Route: typeof R500Route
  AboutRoute: typeof AboutRoute
  AddonsRoute: typeof AddonsRouteWithChildren
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CustomerDisplayRoute: typeof CustomerDisplayRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OgPreviewRoute: typeof OgPreviewRoute
  PortalRoute: typeof PortalRouteWithChildren
  PricingRoute: typeof PricingRoute
  ProductRoute: typeof ProductRoute
  ResourcesRoute: typeof ResourcesRoute
  SolutionsRoute: typeof SolutionsRoute
  StoreRoute: typeof StoreRoute
  SuperLoginRoute: typeof SuperLoginRoute
  Verify2faRoute: typeof Verify2faRoute
  ATagRoute: typeof ATagRoute
  LegalSlugRoute: typeof LegalSlugRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addons': {
      id: '/addons'
      path: '/addons'
      fullPath: '/addons'
      preLoaderRoute: typeof AddonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-display': {
      id: '/customer-display'
      path: '/customer-display'
      fullPath: '/customer-display'
      preLoaderRoute: typeof CustomerDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og-preview': {
      id: '/og-preview'
      path: '/og-preview'
      fullPath: '/og-preview'
      preLoaderRoute: typeof OgPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-login': {
      id: '/super-login'
      path: '/super-login'
      fullPath: '/super-login'
      preLoaderRoute: typeof SuperLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-2fa': {
      id: '/verify-2fa'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof Verify2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super': {
      id: '/_authenticated/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof AuthenticatedSuperRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/a/$tag': {
      id: '/a/$tag'
      path: '/a/$tag'
      fullPath: '/a/$tag'
      preLoaderRoute: typeof ATagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addons/$slug': {
      id: '/addons/$slug'
      path: '/$slug'
      fullPath: '/addons/$slug'
      preLoaderRoute: typeof AddonsSlugRouteImport
      parentRoute: typeof AddonsRoute
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app/accounting': {
      id: '/_authenticated/_app/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AuthenticatedAppAccountingRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/adjustments': {
      id: '/_authenticated/_app/adjustments'
      path: '/adjustments'
      fullPath: '/adjustments'
      preLoaderRoute: typeof AuthenticatedAppAdjustmentsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/ai-ocr': {
      id: '/_authenticated/_app/ai-ocr'
      path: '/ai-ocr'
      fullPath: '/ai-ocr'
      preLoaderRoute: typeof AuthenticatedAppAiOcrRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/ai-writer': {
      id: '/_authenticated/_app/ai-writer'
      path: '/ai-writer'
      fullPath: '/ai-writer'
      preLoaderRoute: typeof AuthenticatedAppAiWriterRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/analytics': {
      id: '/_authenticated/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/announcements': {
      id: '/_authenticated/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAppAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/assets': {
      id: '/_authenticated/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAppAssetsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/attendance': {
      id: '/_authenticated/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAppAttendanceRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/biometric': {
      id: '/_authenticated/_app/biometric'
      path: '/biometric'
      fullPath: '/biometric'
      preLoaderRoute: typeof AuthenticatedAppBiometricRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/biometric-sync': {
      id: '/_authenticated/_app/biometric-sync'
      path: '/biometric-sync'
      fullPath: '/biometric-sync'
      preLoaderRoute: typeof AuthenticatedAppBiometricSyncRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/chat': {
      id: '/_authenticated/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/crm': {
      id: '/_authenticated/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedAppCrmRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/crm-dashboard': {
      id: '/_authenticated/_app/crm-dashboard'
      path: '/crm-dashboard'
      fullPath: '/crm-dashboard'
      preLoaderRoute: typeof AuthenticatedAppCrmDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/documents': {
      id: '/_authenticated/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedAppDocumentsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/employees': {
      id: '/_authenticated/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedAppEmployeesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/expenses': {
      id: '/_authenticated/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedAppExpensesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/finance-dashboard': {
      id: '/_authenticated/_app/finance-dashboard'
      path: '/finance-dashboard'
      fullPath: '/finance-dashboard'
      preLoaderRoute: typeof AuthenticatedAppFinanceDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/forms': {
      id: '/_authenticated/_app/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AuthenticatedAppFormsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/google-workspace': {
      id: '/_authenticated/_app/google-workspace'
      path: '/google-workspace'
      fullPath: '/google-workspace'
      preLoaderRoute: typeof AuthenticatedAppGoogleWorkspaceRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/helpdesk': {
      id: '/_authenticated/_app/helpdesk'
      path: '/helpdesk'
      fullPath: '/helpdesk'
      preLoaderRoute: typeof AuthenticatedAppHelpdeskRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/hrm': {
      id: '/_authenticated/_app/hrm'
      path: '/hrm'
      fullPath: '/hrm'
      preLoaderRoute: typeof AuthenticatedAppHrmRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/integrations': {
      id: '/_authenticated/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/inventory-dashboard': {
      id: '/_authenticated/_app/inventory-dashboard'
      path: '/inventory-dashboard'
      fullPath: '/inventory-dashboard'
      preLoaderRoute: typeof AuthenticatedAppInventoryDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/invoices': {
      id: '/_authenticated/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedAppInvoicesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/leave': {
      id: '/_authenticated/_app/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AuthenticatedAppLeaveRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/marketplace': {
      id: '/_authenticated/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedAppMarketplaceRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/media': {
      id: '/_authenticated/_app/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedAppMediaRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/offboarding': {
      id: '/_authenticated/_app/offboarding'
      path: '/offboarding'
      fullPath: '/offboarding'
      preLoaderRoute: typeof AuthenticatedAppOffboardingRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/okr': {
      id: '/_authenticated/_app/okr'
      path: '/okr'
      fullPath: '/okr'
      preLoaderRoute: typeof AuthenticatedAppOkrRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/payroll': {
      id: '/_authenticated/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedAppPayrollRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/pos': {
      id: '/_authenticated/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedAppPosRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/pos-dashboard': {
      id: '/_authenticated/_app/pos-dashboard'
      path: '/pos-dashboard'
      fullPath: '/pos-dashboard'
      preLoaderRoute: typeof AuthenticatedAppPosDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/procurement-dashboard': {
      id: '/_authenticated/_app/procurement-dashboard'
      path: '/procurement-dashboard'
      fullPath: '/procurement-dashboard'
      preLoaderRoute: typeof AuthenticatedAppProcurementDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/products': {
      id: '/_authenticated/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedAppProductsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/project-dashboard': {
      id: '/_authenticated/_app/project-dashboard'
      path: '/project-dashboard'
      fullPath: '/project-dashboard'
      preLoaderRoute: typeof AuthenticatedAppProjectDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/projects': {
      id: '/_authenticated/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedAppProjectsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/proposals': {
      id: '/_authenticated/_app/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof AuthenticatedAppProposalsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/purchases': {
      id: '/_authenticated/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedAppPurchasesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/razorpay-gateway': {
      id: '/_authenticated/_app/razorpay-gateway'
      path: '/razorpay-gateway'
      fullPath: '/razorpay-gateway'
      preLoaderRoute: typeof AuthenticatedAppRazorpayGatewayRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/recruitment': {
      id: '/_authenticated/_app/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof AuthenticatedAppRecruitmentRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/sales-dashboard': {
      id: '/_authenticated/_app/sales-dashboard'
      path: '/sales-dashboard'
      fullPath: '/sales-dashboard'
      preLoaderRoute: typeof AuthenticatedAppSalesDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/setup-notes': {
      id: '/_authenticated/_app/setup-notes'
      path: '/setup-notes'
      fullPath: '/setup-notes'
      preLoaderRoute: typeof AuthenticatedAppSetupNotesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/shifts': {
      id: '/_authenticated/_app/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthenticatedAppShiftsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/shopify': {
      id: '/_authenticated/_app/shopify'
      path: '/shopify'
      fullPath: '/shopify'
      preLoaderRoute: typeof AuthenticatedAppShopifyRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/subscription': {
      id: '/_authenticated/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedAppSubscriptionRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/suppliers': {
      id: '/_authenticated/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedAppSuppliersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/support': {
      id: '/_authenticated/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedAppSupportRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/support-dashboard': {
      id: '/_authenticated/_app/support-dashboard'
      path: '/support-dashboard'
      fullPath: '/support-dashboard'
      preLoaderRoute: typeof AuthenticatedAppSupportDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/tally-importer': {
      id: '/_authenticated/_app/tally-importer'
      path: '/tally-importer'
      fullPath: '/tally-importer'
      preLoaderRoute: typeof AuthenticatedAppTallyImporterRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/training': {
      id: '/_authenticated/_app/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthenticatedAppTrainingRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/transfers': {
      id: '/_authenticated/_app/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthenticatedAppTransfersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/users': {
      id: '/_authenticated/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedAppUsersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/whatsapp-alerts': {
      id: '/_authenticated/_app/whatsapp-alerts'
      path: '/whatsapp-alerts'
      fullPath: '/whatsapp-alerts'
      preLoaderRoute: typeof AuthenticatedAppWhatsappAlertsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/workflows': {
      id: '/_authenticated/_app/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedAppWorkflowsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/workspace': {
      id: '/_authenticated/_app/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedAppWorkspaceRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/super/': {
      id: '/_authenticated/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof AuthenticatedSuperIndexRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/analytics': {
      id: '/_authenticated/super/analytics'
      path: '/analytics'
      fullPath: '/super/analytics'
      preLoaderRoute: typeof AuthenticatedSuperAnalyticsRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/api-docs': {
      id: '/_authenticated/super/api-docs'
      path: '/api-docs'
      fullPath: '/super/api-docs'
      preLoaderRoute: typeof AuthenticatedSuperApiDocsRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/backup': {
      id: '/_authenticated/super/backup'
      path: '/backup'
      fullPath: '/super/backup'
      preLoaderRoute: typeof AuthenticatedSuperBackupRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/blogs': {
      id: '/_authenticated/super/blogs'
      path: '/blogs'
      fullPath: '/super/blogs'
      preLoaderRoute: typeof AuthenticatedSuperBlogsRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/case-studies': {
      id: '/_authenticated/super/case-studies'
      path: '/case-studies'
      fullPath: '/super/case-studies'
      preLoaderRoute: typeof AuthenticatedSuperCaseStudiesRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/cms': {
      id: '/_authenticated/super/cms'
      path: '/cms'
      fullPath: '/super/cms'
      preLoaderRoute: typeof AuthenticatedSuperCmsRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/email-templates': {
      id: '/_authenticated/super/email-templates'
      path: '/email-templates'
      fullPath: '/super/email-templates'
      preLoaderRoute: typeof AuthenticatedSuperEmailTemplatesRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/languages': {
      id: '/_authenticated/super/languages'
      path: '/languages'
      fullPath: '/super/languages'
      preLoaderRoute: typeof AuthenticatedSuperLanguagesRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/marketplace': {
      id: '/_authenticated/super/marketplace'
      path: '/marketplace'
      fullPath: '/super/marketplace'
      preLoaderRoute: typeof AuthenticatedSuperMarketplaceRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/media': {
      id: '/_authenticated/super/media'
      path: '/media'
      fullPath: '/super/media'
      preLoaderRoute: typeof AuthenticatedSuperMediaRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/notifications': {
      id: '/_authenticated/super/notifications'
      path: '/notifications'
      fullPath: '/super/notifications'
      preLoaderRoute: typeof AuthenticatedSuperNotificationsRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/plans': {
      id: '/_authenticated/super/plans'
      path: '/plans'
      fullPath: '/super/plans'
      preLoaderRoute: typeof AuthenticatedSuperPlansRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/profile': {
      id: '/_authenticated/super/profile'
      path: '/profile'
      fullPath: '/super/profile'
      preLoaderRoute: typeof AuthenticatedSuperProfileRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/roles': {
      id: '/_authenticated/super/roles'
      path: '/roles'
      fullPath: '/super/roles'
      preLoaderRoute: typeof AuthenticatedSuperRolesRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/settings': {
      id: '/_authenticated/super/settings'
      path: '/settings'
      fullPath: '/super/settings'
      preLoaderRoute: typeof AuthenticatedSuperSettingsRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/support': {
      id: '/_authenticated/super/support'
      path: '/support'
      fullPath: '/super/support'
      preLoaderRoute: typeof AuthenticatedSuperSupportRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/tenants': {
      id: '/_authenticated/super/tenants'
      path: '/tenants'
      fullPath: '/super/tenants'
      preLoaderRoute: typeof AuthenticatedSuperTenantsRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/portal/invoices/$id': {
      id: '/portal/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/portal/invoices/$id'
      preLoaderRoute: typeof PortalInvoicesIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/proposals/$id': {
      id: '/portal/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/portal/proposals/$id'
      preLoaderRoute: typeof PortalProposalsIdRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppAccountingRoute: typeof AuthenticatedAppAccountingRoute
  AuthenticatedAppAdjustmentsRoute: typeof AuthenticatedAppAdjustmentsRoute
  AuthenticatedAppAiOcrRoute: typeof AuthenticatedAppAiOcrRoute
  AuthenticatedAppAiWriterRoute: typeof AuthenticatedAppAiWriterRoute
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedAppAnnouncementsRoute: typeof AuthenticatedAppAnnouncementsRoute
  AuthenticatedAppAssetsRoute: typeof AuthenticatedAppAssetsRoute
  AuthenticatedAppAttendanceRoute: typeof AuthenticatedAppAttendanceRoute
  AuthenticatedAppBiometricRoute: typeof AuthenticatedAppBiometricRoute
  AuthenticatedAppBiometricSyncRoute: typeof AuthenticatedAppBiometricSyncRoute
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRoute
  AuthenticatedAppCrmRoute: typeof AuthenticatedAppCrmRoute
  AuthenticatedAppCrmDashboardRoute: typeof AuthenticatedAppCrmDashboardRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppDocumentsRoute: typeof AuthenticatedAppDocumentsRoute
  AuthenticatedAppEmployeesRoute: typeof AuthenticatedAppEmployeesRoute
  AuthenticatedAppExpensesRoute: typeof AuthenticatedAppExpensesRoute
  AuthenticatedAppFinanceDashboardRoute: typeof AuthenticatedAppFinanceDashboardRoute
  AuthenticatedAppFormsRoute: typeof AuthenticatedAppFormsRoute
  AuthenticatedAppGoogleWorkspaceRoute: typeof AuthenticatedAppGoogleWorkspaceRoute
  AuthenticatedAppHelpdeskRoute: typeof AuthenticatedAppHelpdeskRoute
  AuthenticatedAppHrmRoute: typeof AuthenticatedAppHrmRoute
  AuthenticatedAppIntegrationsRoute: typeof AuthenticatedAppIntegrationsRoute
  AuthenticatedAppInventoryDashboardRoute: typeof AuthenticatedAppInventoryDashboardRoute
  AuthenticatedAppInvoicesRoute: typeof AuthenticatedAppInvoicesRoute
  AuthenticatedAppLeaveRoute: typeof AuthenticatedAppLeaveRoute
  AuthenticatedAppMarketplaceRoute: typeof AuthenticatedAppMarketplaceRoute
  AuthenticatedAppMediaRoute: typeof AuthenticatedAppMediaRoute
  AuthenticatedAppOffboardingRoute: typeof AuthenticatedAppOffboardingRoute
  AuthenticatedAppOkrRoute: typeof AuthenticatedAppOkrRoute
  AuthenticatedAppPayrollRoute: typeof AuthenticatedAppPayrollRoute
  AuthenticatedAppPosRoute: typeof AuthenticatedAppPosRoute
  AuthenticatedAppPosDashboardRoute: typeof AuthenticatedAppPosDashboardRoute
  AuthenticatedAppProcurementDashboardRoute: typeof AuthenticatedAppProcurementDashboardRoute
  AuthenticatedAppProductsRoute: typeof AuthenticatedAppProductsRoute
  AuthenticatedAppProjectDashboardRoute: typeof AuthenticatedAppProjectDashboardRoute
  AuthenticatedAppProjectsRoute: typeof AuthenticatedAppProjectsRoute
  AuthenticatedAppProposalsRoute: typeof AuthenticatedAppProposalsRoute
  AuthenticatedAppPurchasesRoute: typeof AuthenticatedAppPurchasesRoute
  AuthenticatedAppRazorpayGatewayRoute: typeof AuthenticatedAppRazorpayGatewayRoute
  AuthenticatedAppRecruitmentRoute: typeof AuthenticatedAppRecruitmentRoute
  AuthenticatedAppSalesDashboardRoute: typeof AuthenticatedAppSalesDashboardRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSetupNotesRoute: typeof AuthenticatedAppSetupNotesRoute
  AuthenticatedAppShiftsRoute: typeof AuthenticatedAppShiftsRoute
  AuthenticatedAppShopifyRoute: typeof AuthenticatedAppShopifyRoute
  AuthenticatedAppSubscriptionRoute: typeof AuthenticatedAppSubscriptionRoute
  AuthenticatedAppSuppliersRoute: typeof AuthenticatedAppSuppliersRoute
  AuthenticatedAppSupportRoute: typeof AuthenticatedAppSupportRoute
  AuthenticatedAppSupportDashboardRoute: typeof AuthenticatedAppSupportDashboardRoute
  AuthenticatedAppTallyImporterRoute: typeof AuthenticatedAppTallyImporterRoute
  AuthenticatedAppTrainingRoute: typeof AuthenticatedAppTrainingRoute
  AuthenticatedAppTransfersRoute: typeof AuthenticatedAppTransfersRoute
  AuthenticatedAppUsersRoute: typeof AuthenticatedAppUsersRoute
  AuthenticatedAppWhatsappAlertsRoute: typeof AuthenticatedAppWhatsappAlertsRoute
  AuthenticatedAppWorkflowsRoute: typeof AuthenticatedAppWorkflowsRoute
  AuthenticatedAppWorkspaceRoute: typeof AuthenticatedAppWorkspaceRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppAccountingRoute: AuthenticatedAppAccountingRoute,
  AuthenticatedAppAdjustmentsRoute: AuthenticatedAppAdjustmentsRoute,
  AuthenticatedAppAiOcrRoute: AuthenticatedAppAiOcrRoute,
  AuthenticatedAppAiWriterRoute: AuthenticatedAppAiWriterRoute,
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedAppAnnouncementsRoute: AuthenticatedAppAnnouncementsRoute,
  AuthenticatedAppAssetsRoute: AuthenticatedAppAssetsRoute,
  AuthenticatedAppAttendanceRoute: AuthenticatedAppAttendanceRoute,
  AuthenticatedAppBiometricRoute: AuthenticatedAppBiometricRoute,
  AuthenticatedAppBiometricSyncRoute: AuthenticatedAppBiometricSyncRoute,
  AuthenticatedAppChatRoute: AuthenticatedAppChatRoute,
  AuthenticatedAppCrmRoute: AuthenticatedAppCrmRoute,
  AuthenticatedAppCrmDashboardRoute: AuthenticatedAppCrmDashboardRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppDocumentsRoute: AuthenticatedAppDocumentsRoute,
  AuthenticatedAppEmployeesRoute: AuthenticatedAppEmployeesRoute,
  AuthenticatedAppExpensesRoute: AuthenticatedAppExpensesRoute,
  AuthenticatedAppFinanceDashboardRoute: AuthenticatedAppFinanceDashboardRoute,
  AuthenticatedAppFormsRoute: AuthenticatedAppFormsRoute,
  AuthenticatedAppGoogleWorkspaceRoute: AuthenticatedAppGoogleWorkspaceRoute,
  AuthenticatedAppHelpdeskRoute: AuthenticatedAppHelpdeskRoute,
  AuthenticatedAppHrmRoute: AuthenticatedAppHrmRoute,
  AuthenticatedAppIntegrationsRoute: AuthenticatedAppIntegrationsRoute,
  AuthenticatedAppInventoryDashboardRoute:
    AuthenticatedAppInventoryDashboardRoute,
  AuthenticatedAppInvoicesRoute: AuthenticatedAppInvoicesRoute,
  AuthenticatedAppLeaveRoute: AuthenticatedAppLeaveRoute,
  AuthenticatedAppMarketplaceRoute: AuthenticatedAppMarketplaceRoute,
  AuthenticatedAppMediaRoute: AuthenticatedAppMediaRoute,
  AuthenticatedAppOffboardingRoute: AuthenticatedAppOffboardingRoute,
  AuthenticatedAppOkrRoute: AuthenticatedAppOkrRoute,
  AuthenticatedAppPayrollRoute: AuthenticatedAppPayrollRoute,
  AuthenticatedAppPosRoute: AuthenticatedAppPosRoute,
  AuthenticatedAppPosDashboardRoute: AuthenticatedAppPosDashboardRoute,
  AuthenticatedAppProcurementDashboardRoute:
    AuthenticatedAppProcurementDashboardRoute,
  AuthenticatedAppProductsRoute: AuthenticatedAppProductsRoute,
  AuthenticatedAppProjectDashboardRoute: AuthenticatedAppProjectDashboardRoute,
  AuthenticatedAppProjectsRoute: AuthenticatedAppProjectsRoute,
  AuthenticatedAppProposalsRoute: AuthenticatedAppProposalsRoute,
  AuthenticatedAppPurchasesRoute: AuthenticatedAppPurchasesRoute,
  AuthenticatedAppRazorpayGatewayRoute: AuthenticatedAppRazorpayGatewayRoute,
  AuthenticatedAppRecruitmentRoute: AuthenticatedAppRecruitmentRoute,
  AuthenticatedAppSalesDashboardRoute: AuthenticatedAppSalesDashboardRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSetupNotesRoute: AuthenticatedAppSetupNotesRoute,
  AuthenticatedAppShiftsRoute: AuthenticatedAppShiftsRoute,
  AuthenticatedAppShopifyRoute: AuthenticatedAppShopifyRoute,
  AuthenticatedAppSubscriptionRoute: AuthenticatedAppSubscriptionRoute,
  AuthenticatedAppSuppliersRoute: AuthenticatedAppSuppliersRoute,
  AuthenticatedAppSupportRoute: AuthenticatedAppSupportRoute,
  AuthenticatedAppSupportDashboardRoute: AuthenticatedAppSupportDashboardRoute,
  AuthenticatedAppTallyImporterRoute: AuthenticatedAppTallyImporterRoute,
  AuthenticatedAppTrainingRoute: AuthenticatedAppTrainingRoute,
  AuthenticatedAppTransfersRoute: AuthenticatedAppTransfersRoute,
  AuthenticatedAppUsersRoute: AuthenticatedAppUsersRoute,
  AuthenticatedAppWhatsappAlertsRoute: AuthenticatedAppWhatsappAlertsRoute,
  AuthenticatedAppWorkflowsRoute: AuthenticatedAppWorkflowsRoute,
  AuthenticatedAppWorkspaceRoute: AuthenticatedAppWorkspaceRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedSuperRouteRouteChildren {
  AuthenticatedSuperAnalyticsRoute: typeof AuthenticatedSuperAnalyticsRoute
  AuthenticatedSuperApiDocsRoute: typeof AuthenticatedSuperApiDocsRoute
  AuthenticatedSuperBackupRoute: typeof AuthenticatedSuperBackupRoute
  AuthenticatedSuperBlogsRoute: typeof AuthenticatedSuperBlogsRoute
  AuthenticatedSuperCaseStudiesRoute: typeof AuthenticatedSuperCaseStudiesRoute
  AuthenticatedSuperCmsRoute: typeof AuthenticatedSuperCmsRoute
  AuthenticatedSuperEmailTemplatesRoute: typeof AuthenticatedSuperEmailTemplatesRoute
  AuthenticatedSuperLanguagesRoute: typeof AuthenticatedSuperLanguagesRoute
  AuthenticatedSuperMarketplaceRoute: typeof AuthenticatedSuperMarketplaceRoute
  AuthenticatedSuperMediaRoute: typeof AuthenticatedSuperMediaRoute
  AuthenticatedSuperNotificationsRoute: typeof AuthenticatedSuperNotificationsRoute
  AuthenticatedSuperPlansRoute: typeof AuthenticatedSuperPlansRoute
  AuthenticatedSuperProfileRoute: typeof AuthenticatedSuperProfileRoute
  AuthenticatedSuperRolesRoute: typeof AuthenticatedSuperRolesRoute
  AuthenticatedSuperSettingsRoute: typeof AuthenticatedSuperSettingsRoute
  AuthenticatedSuperSupportRoute: typeof AuthenticatedSuperSupportRoute
  AuthenticatedSuperTenantsRoute: typeof AuthenticatedSuperTenantsRoute
  AuthenticatedSuperIndexRoute: typeof AuthenticatedSuperIndexRoute
}

const AuthenticatedSuperRouteRouteChildren: AuthenticatedSuperRouteRouteChildren =
  {
    AuthenticatedSuperAnalyticsRoute: AuthenticatedSuperAnalyticsRoute,
    AuthenticatedSuperApiDocsRoute: AuthenticatedSuperApiDocsRoute,
    AuthenticatedSuperBackupRoute: AuthenticatedSuperBackupRoute,
    AuthenticatedSuperBlogsRoute: AuthenticatedSuperBlogsRoute,
    AuthenticatedSuperCaseStudiesRoute: AuthenticatedSuperCaseStudiesRoute,
    AuthenticatedSuperCmsRoute: AuthenticatedSuperCmsRoute,
    AuthenticatedSuperEmailTemplatesRoute:
      AuthenticatedSuperEmailTemplatesRoute,
    AuthenticatedSuperLanguagesRoute: AuthenticatedSuperLanguagesRoute,
    AuthenticatedSuperMarketplaceRoute: AuthenticatedSuperMarketplaceRoute,
    AuthenticatedSuperMediaRoute: AuthenticatedSuperMediaRoute,
    AuthenticatedSuperNotificationsRoute: AuthenticatedSuperNotificationsRoute,
    AuthenticatedSuperPlansRoute: AuthenticatedSuperPlansRoute,
    AuthenticatedSuperProfileRoute: AuthenticatedSuperProfileRoute,
    AuthenticatedSuperRolesRoute: AuthenticatedSuperRolesRoute,
    AuthenticatedSuperSettingsRoute: AuthenticatedSuperSettingsRoute,
    AuthenticatedSuperSupportRoute: AuthenticatedSuperSupportRoute,
    AuthenticatedSuperTenantsRoute: AuthenticatedSuperTenantsRoute,
    AuthenticatedSuperIndexRoute: AuthenticatedSuperIndexRoute,
  }

const AuthenticatedSuperRouteRouteWithChildren =
  AuthenticatedSuperRouteRoute._addFileChildren(
    AuthenticatedSuperRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedSuperRouteRoute: typeof AuthenticatedSuperRouteRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedSuperRouteRoute: AuthenticatedSuperRouteRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AddonsRouteChildren {
  AddonsSlugRoute: typeof AddonsSlugRoute
}

const AddonsRouteChildren: AddonsRouteChildren = {
  AddonsSlugRoute: AddonsSlugRoute,
}

const AddonsRouteWithChildren =
  AddonsRoute._addFileChildren(AddonsRouteChildren)

interface PortalRouteChildren {
  PortalInvoicesIdRoute: typeof PortalInvoicesIdRoute
  PortalProposalsIdRoute: typeof PortalProposalsIdRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalInvoicesIdRoute: PortalInvoicesIdRoute,
  PortalProposalsIdRoute: PortalProposalsIdRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  R404Route: R404Route,
  R500Route: R500Route,
  AboutRoute: AboutRoute,
  AddonsRoute: AddonsRouteWithChildren,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CustomerDisplayRoute: CustomerDisplayRoute,
  MaintenanceRoute: MaintenanceRoute,
  OgPreviewRoute: OgPreviewRoute,
  PortalRoute: PortalRouteWithChildren,
  PricingRoute: PricingRoute,
  ProductRoute: ProductRoute,
  ResourcesRoute: ResourcesRoute,
  SolutionsRoute: SolutionsRoute,
  StoreRoute: StoreRoute,
  SuperLoginRoute: SuperLoginRoute,
  Verify2faRoute: Verify2faRoute,
  ATagRoute: ATagRoute,
  LegalSlugRoute: LegalSlugRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
