/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AddonsRouteImport } from './routes/addons'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as OgPreviewRouteImport } from './routes/og-preview'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProductRouteImport } from './routes/product'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SuperLoginRouteImport } from './routes/super-login'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/_app/route'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSuperRouteRouteImport } from './routes/_authenticated/super/route'
import { Route as AddonsSlugRouteImport } from './routes/addons.$slug'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AuthenticatedAppAccountingRouteImport } from './routes/_authenticated/_app/accounting'
import { Route as AuthenticatedAppAttendanceRouteImport } from './routes/_authenticated/_app/attendance'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/_app/chat'
import { Route as AuthenticatedAppCrmRouteImport } from './routes/_authenticated/_app/crm'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app/dashboard'
import { Route as AuthenticatedAppEmployeesRouteImport } from './routes/_authenticated/_app/employees'
import { Route as AuthenticatedAppHrmRouteImport } from './routes/_authenticated/_app/hrm'
import { Route as AuthenticatedAppInvoicesRouteImport } from './routes/_authenticated/_app/invoices'
import { Route as AuthenticatedAppLeaveRouteImport } from './routes/_authenticated/_app/leave'
import { Route as AuthenticatedAppMarketplaceRouteImport } from './routes/_authenticated/_app/marketplace'
import { Route as AuthenticatedAppMediaRouteImport } from './routes/_authenticated/_app/media'
import { Route as AuthenticatedAppPayrollRouteImport } from './routes/_authenticated/_app/payroll'
import { Route as AuthenticatedAppPosRouteImport } from './routes/_authenticated/_app/pos'
import { Route as AuthenticatedAppProductsRouteImport } from './routes/_authenticated/_app/products'
import { Route as AuthenticatedAppProjectsRouteImport } from './routes/_authenticated/_app/projects'
import { Route as AuthenticatedAppProposalsRouteImport } from './routes/_authenticated/_app/proposals'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/_app/settings'
import { Route as AuthenticatedAppSubscriptionRouteImport } from './routes/_authenticated/_app/subscription'
import { Route as AuthenticatedAppSupportRouteImport } from './routes/_authenticated/_app/support'
import { Route as AuthenticatedAppUsersRouteImport } from './routes/_authenticated/_app/users'
import { Route as AuthenticatedSuperIndexRouteImport } from './routes/_authenticated/super/index'
import { Route as AuthenticatedSuperAnalyticsRouteImport } from './routes/_authenticated/super/analytics'
import { Route as AuthenticatedSuperApiDocsRouteImport } from './routes/_authenticated/super/api-docs'
import { Route as AuthenticatedSuperBackupRouteImport } from './routes/_authenticated/super/backup'
import { Route as AuthenticatedSuperBlogsRouteImport } from './routes/_authenticated/super/blogs'
import { Route as AuthenticatedSuperCmsRouteImport } from './routes/_authenticated/super/cms'
import { Route as AuthenticatedSuperEmailTemplatesRouteImport } from './routes/_authenticated/super/email-templates'
import { Route as AuthenticatedSuperLanguagesRouteImport } from './routes/_authenticated/super/languages'
import { Route as AuthenticatedSuperMarketplaceRouteImport } from './routes/_authenticated/super/marketplace'
import { Route as AuthenticatedSuperMediaRouteImport } from './routes/_authenticated/super/media'
import { Route as AuthenticatedSuperNotificationsRouteImport } from './routes/_authenticated/super/notifications'
import { Route as AuthenticatedSuperPlansRouteImport } from './routes/_authenticated/super/plans'
import { Route as AuthenticatedSuperRolesRouteImport } from './routes/_authenticated/super/roles'
import { Route as AuthenticatedSuperSettingsRouteImport } from './routes/_authenticated/super/settings'
import { Route as AuthenticatedSuperSupportRouteImport } from './routes/_authenticated/super/support'
import { Route as AuthenticatedSuperTenantsRouteImport } from './routes/_authenticated/super/tenants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AddonsRoute = AddonsRouteImport.update({
  id: '/addons',
  path: '/addons',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const OgPreviewRoute = OgPreviewRouteImport.update({
  id: '/og-preview',
  path: '/og-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperLoginRoute = SuperLoginRouteImport.update({
  id: '/super-login',
  path: '/super-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperRouteRoute = AuthenticatedSuperRouteRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AddonsSlugRoute = AddonsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AddonsRoute,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppAccountingRoute =
  AuthenticatedAppAccountingRouteImport.update({
    id: '/accounting',
    path: '/accounting',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAttendanceRoute =
  AuthenticatedAppAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppCrmRoute = AuthenticatedAppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppEmployeesRoute =
  AuthenticatedAppEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppHrmRoute = AuthenticatedAppHrmRouteImport.update({
  id: '/hrm',
  path: '/hrm',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppInvoicesRoute =
  AuthenticatedAppInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppLeaveRoute = AuthenticatedAppLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppMarketplaceRoute =
  AuthenticatedAppMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppMediaRoute = AuthenticatedAppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppPayrollRoute = AuthenticatedAppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppPosRoute = AuthenticatedAppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppProductsRoute =
  AuthenticatedAppProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsRoute =
  AuthenticatedAppProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProposalsRoute =
  AuthenticatedAppProposalsRouteImport.update({
    id: '/proposals',
    path: '/proposals',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSubscriptionRoute =
  AuthenticatedAppSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSupportRoute = AuthenticatedAppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppUsersRoute = AuthenticatedAppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedSuperIndexRoute = AuthenticatedSuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSuperRouteRoute,
} as any)
const AuthenticatedSuperAnalyticsRoute =
  AuthenticatedSuperAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const AuthenticatedSuperApiDocsRoute =
  AuthenticatedSuperApiDocsRouteImport.update({
    id: '/api-docs',
    path: '/api-docs',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const AuthenticatedSuperBackupRoute =
  AuthenticatedSuperBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const AuthenticatedSuperBlogsRoute = AuthenticatedSuperBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AuthenticatedSuperRouteRoute,
} as any)
const AuthenticatedSuperCmsRoute = AuthenticatedSuperCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AuthenticatedSuperRouteRoute,
} as any)
const AuthenticatedSuperEmailTemplatesRoute =
  AuthenticatedSuperEmailTemplatesRouteImport.update({
    id: '/email-templates',
    path: '/email-templates',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const AuthenticatedSuperLanguagesRoute =
  AuthenticatedSuperLanguagesRouteImport.update({
    id: '/languages',
    path: '/languages',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const AuthenticatedSuperMarketplaceRoute =
  AuthenticatedSuperMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const AuthenticatedSuperMediaRoute = AuthenticatedSuperMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedSuperRouteRoute,
} as any)
const AuthenticatedSuperNotificationsRoute =
  AuthenticatedSuperNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const AuthenticatedSuperPlansRoute = AuthenticatedSuperPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedSuperRouteRoute,
} as any)
const AuthenticatedSuperRolesRoute = AuthenticatedSuperRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedSuperRouteRoute,
} as any)
const AuthenticatedSuperSettingsRoute =
  AuthenticatedSuperSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const AuthenticatedSuperSupportRoute =
  AuthenticatedSuperSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)
const AuthenticatedSuperTenantsRoute =
  AuthenticatedSuperTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => AuthenticatedSuperRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/addons': typeof AddonsRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/maintenance': typeof MaintenanceRoute
  '/og-preview': typeof OgPreviewRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRoute
  '/super-login': typeof SuperLoginRoute
  '/super': typeof AuthenticatedSuperRouteRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/addons/$slug': typeof AddonsSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/accounting': typeof AuthenticatedAppAccountingRoute
  '/attendance': typeof AuthenticatedAppAttendanceRoute
  '/chat': typeof AuthenticatedAppChatRoute
  '/crm': typeof AuthenticatedAppCrmRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/employees': typeof AuthenticatedAppEmployeesRoute
  '/hrm': typeof AuthenticatedAppHrmRoute
  '/invoices': typeof AuthenticatedAppInvoicesRoute
  '/leave': typeof AuthenticatedAppLeaveRoute
  '/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/media': typeof AuthenticatedAppMediaRoute
  '/payroll': typeof AuthenticatedAppPayrollRoute
  '/pos': typeof AuthenticatedAppPosRoute
  '/products': typeof AuthenticatedAppProductsRoute
  '/projects': typeof AuthenticatedAppProjectsRoute
  '/proposals': typeof AuthenticatedAppProposalsRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/support': typeof AuthenticatedAppSupportRoute
  '/users': typeof AuthenticatedAppUsersRoute
  '/super/analytics': typeof AuthenticatedSuperAnalyticsRoute
  '/super/api-docs': typeof AuthenticatedSuperApiDocsRoute
  '/super/backup': typeof AuthenticatedSuperBackupRoute
  '/super/blogs': typeof AuthenticatedSuperBlogsRoute
  '/super/cms': typeof AuthenticatedSuperCmsRoute
  '/super/email-templates': typeof AuthenticatedSuperEmailTemplatesRoute
  '/super/languages': typeof AuthenticatedSuperLanguagesRoute
  '/super/marketplace': typeof AuthenticatedSuperMarketplaceRoute
  '/super/media': typeof AuthenticatedSuperMediaRoute
  '/super/notifications': typeof AuthenticatedSuperNotificationsRoute
  '/super/plans': typeof AuthenticatedSuperPlansRoute
  '/super/roles': typeof AuthenticatedSuperRolesRoute
  '/super/settings': typeof AuthenticatedSuperSettingsRoute
  '/super/support': typeof AuthenticatedSuperSupportRoute
  '/super/tenants': typeof AuthenticatedSuperTenantsRoute
  '/super/': typeof AuthenticatedSuperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/addons': typeof AddonsRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/maintenance': typeof MaintenanceRoute
  '/og-preview': typeof OgPreviewRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRoute
  '/super-login': typeof SuperLoginRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/addons/$slug': typeof AddonsSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/accounting': typeof AuthenticatedAppAccountingRoute
  '/attendance': typeof AuthenticatedAppAttendanceRoute
  '/chat': typeof AuthenticatedAppChatRoute
  '/crm': typeof AuthenticatedAppCrmRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/employees': typeof AuthenticatedAppEmployeesRoute
  '/hrm': typeof AuthenticatedAppHrmRoute
  '/invoices': typeof AuthenticatedAppInvoicesRoute
  '/leave': typeof AuthenticatedAppLeaveRoute
  '/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/media': typeof AuthenticatedAppMediaRoute
  '/payroll': typeof AuthenticatedAppPayrollRoute
  '/pos': typeof AuthenticatedAppPosRoute
  '/products': typeof AuthenticatedAppProductsRoute
  '/projects': typeof AuthenticatedAppProjectsRoute
  '/proposals': typeof AuthenticatedAppProposalsRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/support': typeof AuthenticatedAppSupportRoute
  '/users': typeof AuthenticatedAppUsersRoute
  '/super/analytics': typeof AuthenticatedSuperAnalyticsRoute
  '/super/api-docs': typeof AuthenticatedSuperApiDocsRoute
  '/super/backup': typeof AuthenticatedSuperBackupRoute
  '/super/blogs': typeof AuthenticatedSuperBlogsRoute
  '/super/cms': typeof AuthenticatedSuperCmsRoute
  '/super/email-templates': typeof AuthenticatedSuperEmailTemplatesRoute
  '/super/languages': typeof AuthenticatedSuperLanguagesRoute
  '/super/marketplace': typeof AuthenticatedSuperMarketplaceRoute
  '/super/media': typeof AuthenticatedSuperMediaRoute
  '/super/notifications': typeof AuthenticatedSuperNotificationsRoute
  '/super/plans': typeof AuthenticatedSuperPlansRoute
  '/super/roles': typeof AuthenticatedSuperRolesRoute
  '/super/settings': typeof AuthenticatedSuperSettingsRoute
  '/super/support': typeof AuthenticatedSuperSupportRoute
  '/super/tenants': typeof AuthenticatedSuperTenantsRoute
  '/super': typeof AuthenticatedSuperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/addons': typeof AddonsRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/maintenance': typeof MaintenanceRoute
  '/og-preview': typeof OgPreviewRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRoute
  '/super-login': typeof SuperLoginRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/super': typeof AuthenticatedSuperRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/addons/$slug': typeof AddonsSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/_authenticated/_app/accounting': typeof AuthenticatedAppAccountingRoute
  '/_authenticated/_app/attendance': typeof AuthenticatedAppAttendanceRoute
  '/_authenticated/_app/chat': typeof AuthenticatedAppChatRoute
  '/_authenticated/_app/crm': typeof AuthenticatedAppCrmRoute
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/employees': typeof AuthenticatedAppEmployeesRoute
  '/_authenticated/_app/hrm': typeof AuthenticatedAppHrmRoute
  '/_authenticated/_app/invoices': typeof AuthenticatedAppInvoicesRoute
  '/_authenticated/_app/leave': typeof AuthenticatedAppLeaveRoute
  '/_authenticated/_app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/_authenticated/_app/media': typeof AuthenticatedAppMediaRoute
  '/_authenticated/_app/payroll': typeof AuthenticatedAppPayrollRoute
  '/_authenticated/_app/pos': typeof AuthenticatedAppPosRoute
  '/_authenticated/_app/products': typeof AuthenticatedAppProductsRoute
  '/_authenticated/_app/projects': typeof AuthenticatedAppProjectsRoute
  '/_authenticated/_app/proposals': typeof AuthenticatedAppProposalsRoute
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/_app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/_authenticated/_app/support': typeof AuthenticatedAppSupportRoute
  '/_authenticated/_app/users': typeof AuthenticatedAppUsersRoute
  '/_authenticated/super/analytics': typeof AuthenticatedSuperAnalyticsRoute
  '/_authenticated/super/api-docs': typeof AuthenticatedSuperApiDocsRoute
  '/_authenticated/super/backup': typeof AuthenticatedSuperBackupRoute
  '/_authenticated/super/blogs': typeof AuthenticatedSuperBlogsRoute
  '/_authenticated/super/cms': typeof AuthenticatedSuperCmsRoute
  '/_authenticated/super/email-templates': typeof AuthenticatedSuperEmailTemplatesRoute
  '/_authenticated/super/languages': typeof AuthenticatedSuperLanguagesRoute
  '/_authenticated/super/marketplace': typeof AuthenticatedSuperMarketplaceRoute
  '/_authenticated/super/media': typeof AuthenticatedSuperMediaRoute
  '/_authenticated/super/notifications': typeof AuthenticatedSuperNotificationsRoute
  '/_authenticated/super/plans': typeof AuthenticatedSuperPlansRoute
  '/_authenticated/super/roles': typeof AuthenticatedSuperRolesRoute
  '/_authenticated/super/settings': typeof AuthenticatedSuperSettingsRoute
  '/_authenticated/super/support': typeof AuthenticatedSuperSupportRoute
  '/_authenticated/super/tenants': typeof AuthenticatedSuperTenantsRoute
  '/_authenticated/super/': typeof AuthenticatedSuperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/addons'
    | '/auth'
    | '/contact'
    | '/maintenance'
    | '/og-preview'
    | '/pricing'
    | '/product'
    | '/resources'
    | '/solutions'
    | '/super-login'
    | '/super'
    | '/onboarding'
    | '/addons/$slug'
    | '/legal/$slug'
    | '/p/$slug'
    | '/accounting'
    | '/attendance'
    | '/chat'
    | '/crm'
    | '/dashboard'
    | '/employees'
    | '/hrm'
    | '/invoices'
    | '/leave'
    | '/marketplace'
    | '/media'
    | '/payroll'
    | '/pos'
    | '/products'
    | '/projects'
    | '/proposals'
    | '/settings'
    | '/subscription'
    | '/support'
    | '/users'
    | '/super/analytics'
    | '/super/api-docs'
    | '/super/backup'
    | '/super/blogs'
    | '/super/cms'
    | '/super/email-templates'
    | '/super/languages'
    | '/super/marketplace'
    | '/super/media'
    | '/super/notifications'
    | '/super/plans'
    | '/super/roles'
    | '/super/settings'
    | '/super/support'
    | '/super/tenants'
    | '/super/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/addons'
    | '/auth'
    | '/contact'
    | '/maintenance'
    | '/og-preview'
    | '/pricing'
    | '/product'
    | '/resources'
    | '/solutions'
    | '/super-login'
    | '/onboarding'
    | '/addons/$slug'
    | '/legal/$slug'
    | '/p/$slug'
    | '/accounting'
    | '/attendance'
    | '/chat'
    | '/crm'
    | '/dashboard'
    | '/employees'
    | '/hrm'
    | '/invoices'
    | '/leave'
    | '/marketplace'
    | '/media'
    | '/payroll'
    | '/pos'
    | '/products'
    | '/projects'
    | '/proposals'
    | '/settings'
    | '/subscription'
    | '/support'
    | '/users'
    | '/super/analytics'
    | '/super/api-docs'
    | '/super/backup'
    | '/super/blogs'
    | '/super/cms'
    | '/super/email-templates'
    | '/super/languages'
    | '/super/marketplace'
    | '/super/media'
    | '/super/notifications'
    | '/super/plans'
    | '/super/roles'
    | '/super/settings'
    | '/super/support'
    | '/super/tenants'
    | '/super'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/addons'
    | '/auth'
    | '/contact'
    | '/maintenance'
    | '/og-preview'
    | '/pricing'
    | '/product'
    | '/resources'
    | '/solutions'
    | '/super-login'
    | '/_authenticated/_app'
    | '/_authenticated/super'
    | '/_authenticated/onboarding'
    | '/addons/$slug'
    | '/legal/$slug'
    | '/p/$slug'
    | '/_authenticated/_app/accounting'
    | '/_authenticated/_app/attendance'
    | '/_authenticated/_app/chat'
    | '/_authenticated/_app/crm'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/employees'
    | '/_authenticated/_app/hrm'
    | '/_authenticated/_app/invoices'
    | '/_authenticated/_app/leave'
    | '/_authenticated/_app/marketplace'
    | '/_authenticated/_app/media'
    | '/_authenticated/_app/payroll'
    | '/_authenticated/_app/pos'
    | '/_authenticated/_app/products'
    | '/_authenticated/_app/projects'
    | '/_authenticated/_app/proposals'
    | '/_authenticated/_app/settings'
    | '/_authenticated/_app/subscription'
    | '/_authenticated/_app/support'
    | '/_authenticated/_app/users'
    | '/_authenticated/super/analytics'
    | '/_authenticated/super/api-docs'
    | '/_authenticated/super/backup'
    | '/_authenticated/super/blogs'
    | '/_authenticated/super/cms'
    | '/_authenticated/super/email-templates'
    | '/_authenticated/super/languages'
    | '/_authenticated/super/marketplace'
    | '/_authenticated/super/media'
    | '/_authenticated/super/notifications'
    | '/_authenticated/super/plans'
    | '/_authenticated/super/roles'
    | '/_authenticated/super/settings'
    | '/_authenticated/super/support'
    | '/_authenticated/super/tenants'
    | '/_authenticated/super/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AddonsRoute: typeof AddonsRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OgPreviewRoute: typeof OgPreviewRoute
  PricingRoute: typeof PricingRoute
  ProductRoute: typeof ProductRoute
  ResourcesRoute: typeof ResourcesRoute
  SolutionsRoute: typeof SolutionsRoute
  SuperLoginRoute: typeof SuperLoginRoute
  LegalSlugRoute: typeof LegalSlugRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addons': {
      id: '/addons'
      path: '/addons'
      fullPath: '/addons'
      preLoaderRoute: typeof AddonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og-preview': {
      id: '/og-preview'
      path: '/og-preview'
      fullPath: '/og-preview'
      preLoaderRoute: typeof OgPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-login': {
      id: '/super-login'
      path: '/super-login'
      fullPath: '/super-login'
      preLoaderRoute: typeof SuperLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super': {
      id: '/_authenticated/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof AuthenticatedSuperRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/addons/$slug': {
      id: '/addons/$slug'
      path: '/$slug'
      fullPath: '/addons/$slug'
      preLoaderRoute: typeof AddonsSlugRouteImport
      parentRoute: typeof AddonsRoute
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app/accounting': {
      id: '/_authenticated/_app/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AuthenticatedAppAccountingRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/attendance': {
      id: '/_authenticated/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAppAttendanceRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/chat': {
      id: '/_authenticated/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/crm': {
      id: '/_authenticated/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedAppCrmRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/employees': {
      id: '/_authenticated/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedAppEmployeesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/hrm': {
      id: '/_authenticated/_app/hrm'
      path: '/hrm'
      fullPath: '/hrm'
      preLoaderRoute: typeof AuthenticatedAppHrmRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/invoices': {
      id: '/_authenticated/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedAppInvoicesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/leave': {
      id: '/_authenticated/_app/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AuthenticatedAppLeaveRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/marketplace': {
      id: '/_authenticated/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedAppMarketplaceRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/media': {
      id: '/_authenticated/_app/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedAppMediaRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/payroll': {
      id: '/_authenticated/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedAppPayrollRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/pos': {
      id: '/_authenticated/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedAppPosRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/products': {
      id: '/_authenticated/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedAppProductsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/projects': {
      id: '/_authenticated/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedAppProjectsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/proposals': {
      id: '/_authenticated/_app/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof AuthenticatedAppProposalsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/subscription': {
      id: '/_authenticated/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedAppSubscriptionRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/support': {
      id: '/_authenticated/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedAppSupportRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/users': {
      id: '/_authenticated/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedAppUsersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/super/': {
      id: '/_authenticated/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof AuthenticatedSuperIndexRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/analytics': {
      id: '/_authenticated/super/analytics'
      path: '/analytics'
      fullPath: '/super/analytics'
      preLoaderRoute: typeof AuthenticatedSuperAnalyticsRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/api-docs': {
      id: '/_authenticated/super/api-docs'
      path: '/api-docs'
      fullPath: '/super/api-docs'
      preLoaderRoute: typeof AuthenticatedSuperApiDocsRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/backup': {
      id: '/_authenticated/super/backup'
      path: '/backup'
      fullPath: '/super/backup'
      preLoaderRoute: typeof AuthenticatedSuperBackupRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/blogs': {
      id: '/_authenticated/super/blogs'
      path: '/blogs'
      fullPath: '/super/blogs'
      preLoaderRoute: typeof AuthenticatedSuperBlogsRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/cms': {
      id: '/_authenticated/super/cms'
      path: '/cms'
      fullPath: '/super/cms'
      preLoaderRoute: typeof AuthenticatedSuperCmsRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/email-templates': {
      id: '/_authenticated/super/email-templates'
      path: '/email-templates'
      fullPath: '/super/email-templates'
      preLoaderRoute: typeof AuthenticatedSuperEmailTemplatesRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/languages': {
      id: '/_authenticated/super/languages'
      path: '/languages'
      fullPath: '/super/languages'
      preLoaderRoute: typeof AuthenticatedSuperLanguagesRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/marketplace': {
      id: '/_authenticated/super/marketplace'
      path: '/marketplace'
      fullPath: '/super/marketplace'
      preLoaderRoute: typeof AuthenticatedSuperMarketplaceRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/media': {
      id: '/_authenticated/super/media'
      path: '/media'
      fullPath: '/super/media'
      preLoaderRoute: typeof AuthenticatedSuperMediaRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/notifications': {
      id: '/_authenticated/super/notifications'
      path: '/notifications'
      fullPath: '/super/notifications'
      preLoaderRoute: typeof AuthenticatedSuperNotificationsRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/plans': {
      id: '/_authenticated/super/plans'
      path: '/plans'
      fullPath: '/super/plans'
      preLoaderRoute: typeof AuthenticatedSuperPlansRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/roles': {
      id: '/_authenticated/super/roles'
      path: '/roles'
      fullPath: '/super/roles'
      preLoaderRoute: typeof AuthenticatedSuperRolesRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/settings': {
      id: '/_authenticated/super/settings'
      path: '/settings'
      fullPath: '/super/settings'
      preLoaderRoute: typeof AuthenticatedSuperSettingsRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/support': {
      id: '/_authenticated/super/support'
      path: '/support'
      fullPath: '/super/support'
      preLoaderRoute: typeof AuthenticatedSuperSupportRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
    '/_authenticated/super/tenants': {
      id: '/_authenticated/super/tenants'
      path: '/tenants'
      fullPath: '/super/tenants'
      preLoaderRoute: typeof AuthenticatedSuperTenantsRouteImport
      parentRoute: typeof AuthenticatedSuperRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppAccountingRoute: typeof AuthenticatedAppAccountingRoute
  AuthenticatedAppAttendanceRoute: typeof AuthenticatedAppAttendanceRoute
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRoute
  AuthenticatedAppCrmRoute: typeof AuthenticatedAppCrmRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppEmployeesRoute: typeof AuthenticatedAppEmployeesRoute
  AuthenticatedAppHrmRoute: typeof AuthenticatedAppHrmRoute
  AuthenticatedAppInvoicesRoute: typeof AuthenticatedAppInvoicesRoute
  AuthenticatedAppLeaveRoute: typeof AuthenticatedAppLeaveRoute
  AuthenticatedAppMarketplaceRoute: typeof AuthenticatedAppMarketplaceRoute
  AuthenticatedAppMediaRoute: typeof AuthenticatedAppMediaRoute
  AuthenticatedAppPayrollRoute: typeof AuthenticatedAppPayrollRoute
  AuthenticatedAppPosRoute: typeof AuthenticatedAppPosRoute
  AuthenticatedAppProductsRoute: typeof AuthenticatedAppProductsRoute
  AuthenticatedAppProjectsRoute: typeof AuthenticatedAppProjectsRoute
  AuthenticatedAppProposalsRoute: typeof AuthenticatedAppProposalsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSubscriptionRoute: typeof AuthenticatedAppSubscriptionRoute
  AuthenticatedAppSupportRoute: typeof AuthenticatedAppSupportRoute
  AuthenticatedAppUsersRoute: typeof AuthenticatedAppUsersRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppAccountingRoute: AuthenticatedAppAccountingRoute,
  AuthenticatedAppAttendanceRoute: AuthenticatedAppAttendanceRoute,
  AuthenticatedAppChatRoute: AuthenticatedAppChatRoute,
  AuthenticatedAppCrmRoute: AuthenticatedAppCrmRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppEmployeesRoute: AuthenticatedAppEmployeesRoute,
  AuthenticatedAppHrmRoute: AuthenticatedAppHrmRoute,
  AuthenticatedAppInvoicesRoute: AuthenticatedAppInvoicesRoute,
  AuthenticatedAppLeaveRoute: AuthenticatedAppLeaveRoute,
  AuthenticatedAppMarketplaceRoute: AuthenticatedAppMarketplaceRoute,
  AuthenticatedAppMediaRoute: AuthenticatedAppMediaRoute,
  AuthenticatedAppPayrollRoute: AuthenticatedAppPayrollRoute,
  AuthenticatedAppPosRoute: AuthenticatedAppPosRoute,
  AuthenticatedAppProductsRoute: AuthenticatedAppProductsRoute,
  AuthenticatedAppProjectsRoute: AuthenticatedAppProjectsRoute,
  AuthenticatedAppProposalsRoute: AuthenticatedAppProposalsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSubscriptionRoute: AuthenticatedAppSubscriptionRoute,
  AuthenticatedAppSupportRoute: AuthenticatedAppSupportRoute,
  AuthenticatedAppUsersRoute: AuthenticatedAppUsersRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedSuperRouteRouteChildren {
  AuthenticatedSuperAnalyticsRoute: typeof AuthenticatedSuperAnalyticsRoute
  AuthenticatedSuperApiDocsRoute: typeof AuthenticatedSuperApiDocsRoute
  AuthenticatedSuperBackupRoute: typeof AuthenticatedSuperBackupRoute
  AuthenticatedSuperBlogsRoute: typeof AuthenticatedSuperBlogsRoute
  AuthenticatedSuperCmsRoute: typeof AuthenticatedSuperCmsRoute
  AuthenticatedSuperEmailTemplatesRoute: typeof AuthenticatedSuperEmailTemplatesRoute
  AuthenticatedSuperLanguagesRoute: typeof AuthenticatedSuperLanguagesRoute
  AuthenticatedSuperMarketplaceRoute: typeof AuthenticatedSuperMarketplaceRoute
  AuthenticatedSuperMediaRoute: typeof AuthenticatedSuperMediaRoute
  AuthenticatedSuperNotificationsRoute: typeof AuthenticatedSuperNotificationsRoute
  AuthenticatedSuperPlansRoute: typeof AuthenticatedSuperPlansRoute
  AuthenticatedSuperRolesRoute: typeof AuthenticatedSuperRolesRoute
  AuthenticatedSuperSettingsRoute: typeof AuthenticatedSuperSettingsRoute
  AuthenticatedSuperSupportRoute: typeof AuthenticatedSuperSupportRoute
  AuthenticatedSuperTenantsRoute: typeof AuthenticatedSuperTenantsRoute
  AuthenticatedSuperIndexRoute: typeof AuthenticatedSuperIndexRoute
}

const AuthenticatedSuperRouteRouteChildren: AuthenticatedSuperRouteRouteChildren =
  {
    AuthenticatedSuperAnalyticsRoute: AuthenticatedSuperAnalyticsRoute,
    AuthenticatedSuperApiDocsRoute: AuthenticatedSuperApiDocsRoute,
    AuthenticatedSuperBackupRoute: AuthenticatedSuperBackupRoute,
    AuthenticatedSuperBlogsRoute: AuthenticatedSuperBlogsRoute,
    AuthenticatedSuperCmsRoute: AuthenticatedSuperCmsRoute,
    AuthenticatedSuperEmailTemplatesRoute:
      AuthenticatedSuperEmailTemplatesRoute,
    AuthenticatedSuperLanguagesRoute: AuthenticatedSuperLanguagesRoute,
    AuthenticatedSuperMarketplaceRoute: AuthenticatedSuperMarketplaceRoute,
    AuthenticatedSuperMediaRoute: AuthenticatedSuperMediaRoute,
    AuthenticatedSuperNotificationsRoute: AuthenticatedSuperNotificationsRoute,
    AuthenticatedSuperPlansRoute: AuthenticatedSuperPlansRoute,
    AuthenticatedSuperRolesRoute: AuthenticatedSuperRolesRoute,
    AuthenticatedSuperSettingsRoute: AuthenticatedSuperSettingsRoute,
    AuthenticatedSuperSupportRoute: AuthenticatedSuperSupportRoute,
    AuthenticatedSuperTenantsRoute: AuthenticatedSuperTenantsRoute,
    AuthenticatedSuperIndexRoute: AuthenticatedSuperIndexRoute,
  }

const AuthenticatedSuperRouteRouteWithChildren =
  AuthenticatedSuperRouteRoute._addFileChildren(
    AuthenticatedSuperRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedSuperRouteRoute: typeof AuthenticatedSuperRouteRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedSuperRouteRoute: AuthenticatedSuperRouteRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AddonsRouteChildren {
  AddonsSlugRoute: typeof AddonsSlugRoute
}

const AddonsRouteChildren: AddonsRouteChildren = {
  AddonsSlugRoute: AddonsSlugRoute,
}

const AddonsRouteWithChildren =
  AddonsRoute._addFileChildren(AddonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AddonsRoute: AddonsRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  MaintenanceRoute: MaintenanceRoute,
  OgPreviewRoute: OgPreviewRoute,
  PricingRoute: PricingRoute,
  ProductRoute: ProductRoute,
  ResourcesRoute: ResourcesRoute,
  SolutionsRoute: SolutionsRoute,
  SuperLoginRoute: SuperLoginRoute,
  LegalSlugRoute: LegalSlugRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
