/**
 * MASTERHRMS — Navigation Registry
 * 
 * Defines all navigation menus as data:
 * - id, portal, heading, label, path, icon, moduleKey, permission, planFeature, children[]
 * - Every path is bound to ROUTES constants from "@/lib/routes"
 */

import { ROUTES } from "@/lib/routes";

export type PortalId = "tenant" | "hr" | "me" | "sa" | "client";

export interface NavRegistryItem {
  id: string;
  portal: PortalId;
  heading: string;
  label: string;
  path: string;
  icon: string;
  moduleKey?: string;
  permission?: string;
  planFeature?: string;
  exactMatch?: boolean;
  order: number;
  children?: NavRegistryItem[];
}

export interface NavigationFilterContext {
  roles?: string[];
  permissions?: string[];
  enabledModules?: string[];
  isSuperAdmin?: boolean;
  isTenantAdmin?: boolean;
  activePortal?: PortalId;
}

// ─────────────────────────────────────────────────────────────
// 1. HR SIDEBAR REGISTRY (/hr/*) — Exact Section 4.1 Order
// ─────────────────────────────────────────────────────────────
export const HR_NAVIGATION_REGISTRY: NavRegistryItem[] = [
  // 1. Overview
  {
    id: "hr-dashboard",
    portal: "hr",
    heading: "1. Overview",
    label: "Dashboard",
    path: ROUTES.hr.dashboard,
    icon: "LayoutDashboard",
    order: 10,
    exactMatch: true,
  },
  {
    id: "hr-calendar",
    portal: "hr",
    heading: "1. Overview",
    label: "Calendar",
    path: ROUTES.hr.calendar,
    icon: "Calendar",
    order: 20,
  },
  {
    id: "hr-chat",
    portal: "hr",
    heading: "1. Overview",
    label: "Chat",
    path: ROUTES.hr.chat,
    icon: "MessageSquare",
    order: 30,
  },

  // 2. Workforce Management
  {
    id: "hr-employees",
    portal: "hr",
    heading: "2. Workforce Management",
    label: "Employees",
    path: ROUTES.hr.employees,
    icon: "Users",
    order: 40,
  },
  {
    id: "hr-org-structure",
    portal: "hr",
    heading: "2. Workforce Management",
    label: "Organization Structure",
    path: ROUTES.hr.organization.departments,
    icon: "Building2",
    order: 50,
    children: [
      {
        id: "hr-org-branches",
        portal: "hr",
        heading: "2. Workforce Management",
        label: "Branches",
        path: ROUTES.hr.organization.branches,
        icon: "GitBranch",
        order: 51,
      },
      {
        id: "hr-org-departments",
        portal: "hr",
        heading: "2. Workforce Management",
        label: "Departments",
        path: ROUTES.hr.organization.departments,
        icon: "Building2",
        order: 52,
      },
      {
        id: "hr-org-designations",
        portal: "hr",
        heading: "2. Workforce Management",
        label: "Designations",
        path: ROUTES.hr.organization.designations,
        icon: "Award",
        order: 53,
      },
      {
        id: "hr-org-holidays",
        portal: "hr",
        heading: "2. Workforce Management",
        label: "Holiday",
        path: ROUTES.hr.organization.holidays,
        icon: "CalendarDays",
        order: 54,
      },
      {
        id: "hr-org-announcements",
        portal: "hr",
        heading: "2. Workforce Management",
        label: "Announcements",
        path: ROUTES.hr.organization.announcements,
        icon: "Megaphone",
        order: 55,
      },
      {
        id: "hr-org-award-types",
        portal: "hr",
        heading: "2. Workforce Management",
        label: "Award Types",
        path: ROUTES.hr.organization.awardTypes,
        icon: "Trophy",
        order: 56,
      },
      {
        id: "hr-org-document-types",
        portal: "hr",
        heading: "2. Workforce Management",
        label: "Document Types",
        path: ROUTES.hr.organization.documentTypes,
        icon: "FileText",
        order: 57,
      },
    ],
  },
  {
    id: "hr-attendance",
    portal: "hr",
    heading: "2. Workforce Management",
    label: "Attendance",
    path: ROUTES.hr.attendance.root,
    icon: "Clock",
    order: 60,
    children: [
      {
        id: "hr-attendance-records",
        portal: "hr",
        heading: "2. Workforce Management",
        label: "Attendance Records",
        path: ROUTES.hr.attendance.records,
        icon: "Clock",
        order: 61,
      },
      {
        id: "hr-attendance-timesheets",
        portal: "hr",
        heading: "2. Workforce Management",
        label: "Timesheet",
        path: ROUTES.hr.attendance.timesheets,
        icon: "CalendarCheck",
        order: 62,
      },
      {
        id: "hr-attendance-regularizations",
        portal: "hr",
        heading: "2. Workforce Management",
        label: "Attendance Regularizations",
        path: ROUTES.hr.attendance.regularizations,
        icon: "CheckCheck",
        order: 63,
      },
      {
        id: "hr-attendance-shifts",
        portal: "hr",
        heading: "2. Workforce Management",
        label: "Shifts",
        path: ROUTES.hr.attendance.shifts,
        icon: "Timer",
        order: 64,
      },
      {
        id: "hr-attendance-policies",
        portal: "hr",
        heading: "2. Workforce Management",
        label: "Attendance Policy",
        path: ROUTES.hr.attendance.policies,
        icon: "ShieldAlert",
        order: 65,
      },
    ],
  },
  {
    id: "hr-leave",
    portal: "hr",
    heading: "2. Workforce Management",
    label: "Leave Management",
    path: ROUTES.hr.leave.applications,
    icon: "CalendarCheck",
    order: 70,
    children: [
      {
        id: "hr-leave-applications",
        portal: "hr",
        heading: "2. Workforce Management",
        label: "Leave Applications",
        path: ROUTES.hr.leave.applications,
        icon: "CalendarCheck",
        order: 71,
      },
      {
        id: "hr-leave-balances",
        portal: "hr",
        heading: "2. Workforce Management",
        label: "Leave Balances",
        path: ROUTES.hr.leave.balances,
        icon: "Scale",
        order: 72,
      },
      {
        id: "hr-leave-types",
        portal: "hr",
        heading: "2. Workforce Management",
        label: "Leave Types",
        path: ROUTES.hr.leave.types,
        icon: "Layers",
        order: 73,
      },
      {
        id: "hr-leave-policies",
        portal: "hr",
        heading: "2. Workforce Management",
        label: "Leave Policies",
        path: ROUTES.hr.leave.policies,
        icon: "FileCheck",
        order: 74,
      },
    ],
  },

  // 3. Talent and Growth
  {
    id: "hr-recruitment",
    portal: "hr",
    heading: "3. Talent and Growth",
    label: "Recruitment",
    path: ROUTES.hr.recruitment.jobPostings,
    icon: "Briefcase",
    order: 80,
    children: [
      {
        id: "hr-recruitment-job-postings",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Job Postings",
        path: ROUTES.hr.recruitment.jobPostings,
        icon: "Briefcase",
        order: 81,
      },
      {
        id: "hr-recruitment-candidates",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Candidates",
        path: ROUTES.hr.recruitment.candidates,
        icon: "UserCheck",
        order: 82,
      },
      {
        id: "hr-recruitment-interviews",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Interviews",
        path: ROUTES.hr.recruitment.interviews,
        icon: "Calendar",
        order: 83,
      },
      {
        id: "hr-recruitment-offers",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Offers",
        path: ROUTES.hr.recruitment.offers,
        icon: "Gift",
        order: 84,
      },
      {
        id: "hr-recruitment-candidate-onboarding",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Candidate Onboarding",
        path: ROUTES.hr.recruitment.candidateOnboarding,
        icon: "UserPlus",
        order: 85,
      },
      {
        id: "hr-recruitment-assessments",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Candidate Assessments",
        path: ROUTES.hr.recruitment.assessments,
        icon: "CheckCircle2",
        order: 86,
      },
      {
        id: "hr-recruitment-onboarding-checklists",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Onboarding Checklists",
        path: ROUTES.hr.recruitment.onboardingChecklists,
        icon: "CheckSquare",
        order: 87,
      },
      {
        id: "hr-recruitment-check-items",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Check Items",
        path: ROUTES.hr.recruitment.checkItems,
        icon: "ListChecks",
        order: 88,
      },
      {
        id: "hr-recruitment-career",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Career",
        path: ROUTES.hr.recruitment.careerSite,
        icon: "Globe",
        order: 89,
      },
      {
        id: "hr-recruitment-job-categories",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Job Categories",
        path: ROUTES.hr.recruitment.jobCategories,
        icon: "Tag",
        order: 90,
      },
      {
        id: "hr-recruitment-job-types",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Job Types",
        path: ROUTES.hr.recruitment.jobTypes,
        icon: "Layers",
        order: 91,
      },
      {
        id: "hr-recruitment-job-locations",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Job Locations",
        path: ROUTES.hr.recruitment.jobLocations,
        icon: "MapPin",
        order: 92,
      },
      {
        id: "hr-recruitment-candidate-sources",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Candidate Sources",
        path: ROUTES.hr.recruitment.candidateSources,
        icon: "Compass",
        order: 93,
      },
      {
        id: "hr-recruitment-interview-types",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Interview Types",
        path: ROUTES.hr.recruitment.interviewTypes,
        icon: "Video",
        order: 94,
      },
      {
        id: "hr-recruitment-interview-rounds",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Interview Rounds",
        path: ROUTES.hr.recruitment.interviewRounds,
        icon: "Repeat",
        order: 95,
      },
      {
        id: "hr-recruitment-offer-templates",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Offer Templates",
        path: ROUTES.hr.recruitment.offerTemplates,
        icon: "FileText",
        order: 96,
      },
    ],
  },
  {
    id: "hr-lifecycle",
    portal: "hr",
    heading: "3. Talent and Growth",
    label: "Employee Lifecycle",
    path: ROUTES.hr.lifecycle.awards,
    icon: "TrendingUp",
    order: 100,
    children: [
      {
        id: "hr-lifecycle-awards",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Awards",
        path: ROUTES.hr.lifecycle.awards,
        icon: "Trophy",
        order: 101,
      },
      {
        id: "hr-lifecycle-promotions",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Promotions",
        path: ROUTES.hr.lifecycle.promotions,
        icon: "TrendingUp",
        order: 102,
      },
      {
        id: "hr-lifecycle-transfers",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Transfers",
        path: ROUTES.hr.lifecycle.transfers,
        icon: "ArrowRightLeft",
        order: 103,
      },
      {
        id: "hr-lifecycle-warnings",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Warnings",
        path: ROUTES.hr.lifecycle.warnings,
        icon: "ShieldAlert",
        order: 104,
      },
      {
        id: "hr-lifecycle-resignations",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Resignations",
        path: ROUTES.hr.lifecycle.resignations,
        icon: "UserMinus",
        order: 105,
      },
      {
        id: "hr-lifecycle-terminations",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Terminations",
        path: ROUTES.hr.lifecycle.terminations,
        icon: "UserX",
        order: 106,
      },
      {
        id: "hr-lifecycle-trips",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Trips",
        path: ROUTES.hr.lifecycle.trips,
        icon: "Plane",
        order: 107,
      },
      {
        id: "hr-lifecycle-complaints",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Complaints",
        path: ROUTES.hr.lifecycle.complaints,
        icon: "AlertCircle",
        order: 108,
      },
    ],
  },
  {
    id: "hr-performance",
    portal: "hr",
    heading: "3. Talent and Growth",
    label: "Performance Management",
    path: ROUTES.hr.performance.reviews,
    icon: "Target",
    order: 110,
    children: [
      {
        id: "hr-performance-reviews",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Employee Reviews",
        path: ROUTES.hr.performance.reviews,
        icon: "FileCheck",
        order: 111,
      },
      {
        id: "hr-performance-goals",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Employee Goals",
        path: ROUTES.hr.performance.goals,
        icon: "Target",
        order: 112,
      },
      {
        id: "hr-performance-cycles",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Review Cycles",
        path: ROUTES.hr.performance.cycles,
        icon: "RotateCw",
        order: 113,
      },
      {
        id: "hr-performance-indicators",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Indicators",
        path: ROUTES.hr.performance.indicators,
        icon: "Sliders",
        order: 114,
      },
      {
        id: "hr-performance-goal-types",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Goal Types",
        path: ROUTES.hr.performance.goalTypes,
        icon: "Layers",
        order: 115,
      },
      {
        id: "hr-performance-indicator-categories",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Indicator Categories",
        path: ROUTES.hr.performance.indicatorCategories,
        icon: "Tag",
        order: 116,
      },
    ],
  },
  {
    id: "hr-training",
    portal: "hr",
    heading: "3. Talent and Growth",
    label: "Training and Development",
    path: ROUTES.hr.training.employeeTrainings,
    icon: "GraduationCap",
    order: 120,
    children: [
      {
        id: "hr-training-employee-trainings",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Employee Trainings",
        path: ROUTES.hr.training.employeeTrainings,
        icon: "GraduationCap",
        order: 121,
      },
      {
        id: "hr-training-sessions",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Training Sessions",
        path: ROUTES.hr.training.sessions,
        icon: "Calendar",
        order: 122,
      },
      {
        id: "hr-training-programs",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Training Programs",
        path: ROUTES.hr.training.programs,
        icon: "BookOpen",
        order: 123,
      },
      {
        id: "hr-training-types",
        portal: "hr",
        heading: "3. Talent and Growth",
        label: "Training Types",
        path: ROUTES.hr.training.types,
        icon: "Tag",
        order: 124,
      },
    ],
  },

  // 4. Finance and Assets
  {
    id: "hr-payroll",
    portal: "hr",
    heading: "4. Finance and Assets",
    label: "Payroll Management",
    path: ROUTES.hr.payroll.payslips,
    icon: "Wallet",
    order: 130,
    children: [
      {
        id: "hr-payroll-payslips",
        portal: "hr",
        heading: "4. Finance and Assets",
        label: "Payslips",
        path: ROUTES.hr.payroll.payslips,
        icon: "Receipt",
        order: 131,
      },
      {
        id: "hr-payroll-runs",
        portal: "hr",
        heading: "4. Finance and Assets",
        label: "Payroll Runs",
        path: ROUTES.hr.payroll.runs,
        icon: "PlayCircle",
        order: 132,
      },
      {
        id: "hr-payroll-employee-salaries",
        portal: "hr",
        heading: "4. Finance and Assets",
        label: "Employee Salaries",
        path: ROUTES.hr.payroll.employeeSalaries,
        icon: "DollarSign",
        order: 133,
      },
      {
        id: "hr-payroll-components",
        portal: "hr",
        heading: "4. Finance and Assets",
        label: "Salary Components",
        path: ROUTES.hr.payroll.components,
        icon: "Percent",
        order: 134,
      },
    ],
  },
  {
    id: "hr-assets",
    portal: "hr",
    heading: "4. Finance and Assets",
    label: "Asset Management",
    path: ROUTES.hr.assets.list,
    icon: "Package",
    order: 140,
    children: [
      {
        id: "hr-assets-dashboard",
        portal: "hr",
        heading: "4. Finance and Assets",
        label: "Dashboard",
        path: ROUTES.hr.assets.dashboard,
        icon: "LayoutDashboard",
        order: 141,
      },
      {
        id: "hr-assets-list",
        portal: "hr",
        heading: "4. Finance and Assets",
        label: "Assets",
        path: ROUTES.hr.assets.list,
        icon: "Package",
        order: 142,
      },
      {
        id: "hr-assets-depreciation",
        portal: "hr",
        heading: "4. Finance and Assets",
        label: "Depreciation",
        path: ROUTES.hr.assets.depreciation,
        icon: "TrendingDown",
        order: 143,
      },
      {
        id: "hr-assets-types",
        portal: "hr",
        heading: "4. Finance and Assets",
        label: "Asset Types",
        path: ROUTES.hr.assets.types,
        icon: "Layers",
        order: 144,
      },
    ],
  },

  // 5. Communication and Content
  {
    id: "hr-meetings",
    portal: "hr",
    heading: "5. Communication and Content",
    label: "Meeting",
    path: ROUTES.hr.meetings.list,
    icon: "Users2",
    order: 150,
    children: [
      {
        id: "hr-meetings-list",
        portal: "hr",
        heading: "5. Communication and Content",
        label: "Meetings",
        path: ROUTES.hr.meetings.list,
        icon: "Calendar",
        order: 151,
      },
      {
        id: "hr-meetings-action-items",
        portal: "hr",
        heading: "5. Communication and Content",
        label: "Action Items",
        path: ROUTES.hr.meetings.actionItems,
        icon: "CheckSquare",
        order: 152,
      },
      {
        id: "hr-meetings-types",
        portal: "hr",
        heading: "5. Communication and Content",
        label: "Meeting Types",
        path: ROUTES.hr.meetings.types,
        icon: "Tag",
        order: 153,
      },
      {
        id: "hr-meetings-rooms",
        portal: "hr",
        heading: "5. Communication and Content",
        label: "Meeting Rooms",
        path: ROUTES.hr.meetings.rooms,
        icon: "DoorOpen",
        order: 154,
      },
    ],
  },
  {
    id: "hr-documents",
    portal: "hr",
    heading: "5. Communication and Content",
    label: "Document and Contract",
    path: ROUTES.hr.documents.list,
    icon: "FileText",
    order: 160,
    children: [
      {
        id: "hr-documents-list",
        portal: "hr",
        heading: "5. Communication and Content",
        label: "HR Documents",
        path: ROUTES.hr.documents.list,
        icon: "FileText",
        order: 161,
      },
      {
        id: "hr-documents-contracts",
        portal: "hr",
        heading: "5. Communication and Content",
        label: "Employee Contracts",
        path: ROUTES.hr.documents.contracts,
        icon: "FileCheck",
        order: 162,
      },
      {
        id: "hr-documents-acknowledgements",
        portal: "hr",
        heading: "5. Communication and Content",
        label: "Acknowledgements",
        path: ROUTES.hr.documents.acknowledgements,
        icon: "CheckCircle",
        order: 163,
      },
      {
        id: "hr-documents-contract-templates",
        portal: "hr",
        heading: "5. Communication and Content",
        label: "Contract Templates",
        path: ROUTES.hr.documents.contractTemplates,
        icon: "FileSignature",
        order: 164,
      },
      {
        id: "hr-documents-document-templates",
        portal: "hr",
        heading: "5. Communication and Content",
        label: "Document Templates",
        path: ROUTES.hr.documents.documentTemplates,
        icon: "Copy",
        order: 165,
      },
      {
        id: "hr-documents-contract-types",
        portal: "hr",
        heading: "5. Communication and Content",
        label: "Contract Types",
        path: ROUTES.hr.documents.contractTypes,
        icon: "Tag",
        order: 166,
      },
      {
        id: "hr-documents-categories",
        portal: "hr",
        heading: "5. Communication and Content",
        label: "Document Category",
        path: ROUTES.hr.documents.categories,
        icon: "Folder",
        order: 167,
      },
    ],
  },
  {
    id: "hr-media",
    portal: "hr",
    heading: "5. Communication and Content",
    label: "Media Library",
    path: ROUTES.hr.media,
    icon: "Image",
    order: 170,
  },
  {
    id: "hr-profile",
    portal: "hr",
    heading: "5. Communication and Content",
    label: "My Profile",
    path: ROUTES.hr.profile,
    icon: "User",
    order: 180,
  },
];

// ─────────────────────────────────────────────────────────────
// 2. EMPLOYEE SIDEBAR REGISTRY (/me/*) — Exact Section 4.2 Order
// ─────────────────────────────────────────────────────────────
export const EMPLOYEE_NAVIGATION_REGISTRY: NavRegistryItem[] = [
  // 1. Overview
  {
    id: "me-dashboard",
    portal: "me",
    heading: "1. Overview",
    label: "Dashboard",
    path: ROUTES.me.dashboard,
    icon: "LayoutDashboard",
    order: 10,
    exactMatch: true,
  },
  {
    id: "me-calendar",
    portal: "me",
    heading: "1. Overview",
    label: "Calendar",
    path: ROUTES.me.calendar,
    icon: "Calendar",
    order: 20,
  },
  {
    id: "me-todo",
    portal: "me",
    heading: "1. Overview",
    label: "Todo",
    path: ROUTES.me.todo,
    icon: "CheckSquare",
    order: 30,
  },
  {
    id: "me-chat",
    portal: "me",
    heading: "1. Overview",
    label: "Chat",
    path: ROUTES.me.chat,
    icon: "MessageSquare",
    order: 40,
  },
  {
    id: "me-notifications",
    portal: "me",
    heading: "1. Overview",
    label: "Notifications",
    path: ROUTES.me.notifications,
    icon: "Bell",
    order: 50,
  },

  // 2. Workspace Management
  {
    id: "me-employees",
    portal: "me",
    heading: "2. Workspace Management",
    label: "Employee Directory",
    path: ROUTES.me.employees,
    icon: "Users",
    order: 60,
  },
  {
    id: "me-org-structure",
    portal: "me",
    heading: "2. Workspace Management",
    label: "Organization Structure",
    path: ROUTES.me.organization.holidays,
    icon: "Building2",
    order: 70,
    children: [
      {
        id: "me-org-holidays",
        portal: "me",
        heading: "2. Workspace Management",
        label: "Holidays",
        path: ROUTES.me.organization.holidays,
        icon: "CalendarDays",
        order: 71,
      },
      {
        id: "me-org-announcements",
        portal: "me",
        heading: "2. Workspace Management",
        label: "Announcements",
        path: ROUTES.me.organization.announcements,
        icon: "Megaphone",
        order: 72,
      },
    ],
  },
  {
    id: "me-attendance",
    portal: "me",
    heading: "2. Workspace Management",
    label: "Attendance",
    path: ROUTES.me.attendance.records,
    icon: "Clock",
    order: 80,
    children: [
      {
        id: "me-attendance-records",
        portal: "me",
        heading: "2. Workspace Management",
        label: "Attendance Records",
        path: ROUTES.me.attendance.records,
        icon: "Clock",
        order: 81,
      },
      {
        id: "me-attendance-timesheet",
        portal: "me",
        heading: "2. Workspace Management",
        label: "Timesheet",
        path: ROUTES.me.attendance.timesheet,
        icon: "CalendarCheck",
        order: 82,
      },
      {
        id: "me-attendance-regularizations",
        portal: "me",
        heading: "2. Workspace Management",
        label: "Regularizations",
        path: ROUTES.me.attendance.regularizations,
        icon: "CheckCheck",
        order: 83,
      },
      {
        id: "me-attendance-shifts",
        portal: "me",
        heading: "2. Workspace Management",
        label: "Shift",
        path: ROUTES.me.attendance.shifts,
        icon: "Timer",
        order: 84,
      },
      {
        id: "me-attendance-policies",
        portal: "me",
        heading: "2. Workspace Management",
        label: "Attendance Policies",
        path: ROUTES.me.attendance.policies,
        icon: "ShieldAlert",
        order: 85,
      },
      {
        id: "me-attendance-requests",
        portal: "me",
        heading: "2. Workspace Management",
        label: "Requests",
        path: ROUTES.me.attendance.requests,
        icon: "Send",
        order: 86,
      },
    ],
  },
  {
    id: "me-leave",
    portal: "me",
    heading: "2. Workspace Management",
    label: "Leave Management",
    path: ROUTES.me.leave.applications,
    icon: "CalendarCheck",
    order: 90,
    children: [
      {
        id: "me-leave-applications",
        portal: "me",
        heading: "2. Workspace Management",
        label: "Leave Applications",
        path: ROUTES.me.leave.applications,
        icon: "CalendarCheck",
        order: 91,
      },
      {
        id: "me-leave-balance",
        portal: "me",
        heading: "2. Workspace Management",
        label: "Leave Balance",
        path: ROUTES.me.leave.balance,
        icon: "Scale",
        order: 92,
      },
      {
        id: "me-leave-policies",
        portal: "me",
        heading: "2. Workspace Management",
        label: "Leave Policies",
        path: ROUTES.me.leave.policies,
        icon: "FileCheck",
        order: 93,
      },
      {
        id: "me-leave-team-calendar",
        portal: "me",
        heading: "2. Workspace Management",
        label: "Team Calendar",
        path: ROUTES.me.leave.teamCalendar,
        icon: "Calendar",
        order: 94,
      },
    ],
  },

  // 3. Talent & Growth
  {
    id: "me-recruitment",
    portal: "me",
    heading: "3. Talent & Growth",
    label: "Recruitment",
    path: ROUTES.me.recruitment.jobPostings,
    icon: "Briefcase",
    order: 100,
    children: [
      {
        id: "me-recruitment-job-postings",
        portal: "me",
        heading: "3. Talent & Growth",
        label: "Job Postings",
        path: ROUTES.me.recruitment.jobPostings,
        icon: "Briefcase",
        order: 101,
      },
      {
        id: "me-recruitment-interviews",
        portal: "me",
        heading: "3. Talent & Growth",
        label: "Interviews",
        path: ROUTES.me.recruitment.interviews,
        icon: "Calendar",
        order: 102,
      },
      {
        id: "me-recruitment-onboarding",
        portal: "me",
        heading: "3. Talent & Growth",
        label: "My Onboarding",
        path: ROUTES.me.recruitment.onboarding,
        icon: "UserPlus",
        order: 103,
      },
      {
        id: "me-recruitment-assessments",
        portal: "me",
        heading: "3. Talent & Growth",
        label: "My Assessments",
        path: ROUTES.me.recruitment.assessments,
        icon: "CheckCircle2",
        order: 104,
      },
      {
        id: "me-recruitment-career",
        portal: "me",
        heading: "3. Talent & Growth",
        label: "Career & Referrals",
        path: ROUTES.me.recruitment.career,
        icon: "Globe",
        order: 105,
      },
    ],
  },
  {
    id: "me-lifecycle",
    portal: "me",
    heading: "3. Talent & Growth",
    label: "Employee Lifecycle",
    path: ROUTES.me.lifecycle.awards,
    icon: "TrendingUp",
    order: 110,
    children: [
      {
        id: "me-lifecycle-awards",
        portal: "me",
        heading: "3. Talent & Growth",
        label: "Awards",
        path: ROUTES.me.lifecycle.awards,
        icon: "Trophy",
        order: 111,
      },
      {
        id: "me-lifecycle-promotions",
        portal: "me",
        heading: "3. Talent & Growth",
        label: "Promotions",
        path: ROUTES.me.lifecycle.promotions,
        icon: "TrendingUp",
        order: 112,
      },
      {
        id: "me-lifecycle-transfers",
        portal: "me",
        heading: "3. Talent & Growth",
        label: "Transfers",
        path: ROUTES.me.lifecycle.transfers,
        icon: "ArrowRightLeft",
        order: 113,
      },
      {
        id: "me-lifecycle-warnings",
        portal: "me",
        heading: "3. Talent & Growth",
        label: "Warnings",
        path: ROUTES.me.lifecycle.warnings,
        icon: "ShieldAlert",
        order: 114,
      },
      {
        id: "me-lifecycle-resignation",
        portal: "me",
        heading: "3. Talent & Growth",
        label: "Resignation",
        path: ROUTES.me.lifecycle.resignation,
        icon: "UserMinus",
        order: 115,
      },
      {
        id: "me-lifecycle-exit",
        portal: "me",
        heading: "3. Talent & Growth",
        label: "My Exit",
        path: ROUTES.me.lifecycle.exit,
        icon: "DoorOpen",
        order: 116,
      },
      {
        id: "me-lifecycle-trips",
        portal: "me",
        heading: "3. Talent & Growth",
        label: "Trips",
        path: ROUTES.me.lifecycle.trips,
        icon: "Plane",
        order: 117,
      },
      {
        id: "me-lifecycle-complaints",
        portal: "me",
        heading: "3. Talent & Growth",
        label: "Complaints",
        path: ROUTES.me.lifecycle.complaints,
        icon: "AlertCircle",
        order: 118,
      },
    ],
  },
  {
    id: "me-performance",
    portal: "me",
    heading: "3. Talent & Growth",
    label: "Performance Management",
    path: ROUTES.me.performance.reviews,
    icon: "Target",
    order: 120,
    children: [
      {
        id: "me-performance-reviews",
        portal: "me",
        heading: "3. Talent & Growth",
        label: "Reviews",
        path: ROUTES.me.performance.reviews,
        icon: "FileCheck",
        order: 121,
      },
      {
        id: "me-performance-goals",
        portal: "me",
        heading: "3. Talent & Growth",
        label: "Goals",
        path: ROUTES.me.performance.goals,
        icon: "Target",
        order: 122,
      },
      {
        id: "me-performance-cycles",
        portal: "me",
        heading: "3. Talent & Growth",
        label: "Review Cycles",
        path: ROUTES.me.performance.cycles,
        icon: "RotateCw",
        order: 123,
      },
      {
        id: "me-performance-indicators",
        portal: "me",
        heading: "3. Talent & Growth",
        label: "Indicators",
        path: ROUTES.me.performance.indicators,
        icon: "Sliders",
        order: 124,
      },
    ],
  },
  {
    id: "me-training",
    portal: "me",
    heading: "3. Talent & Growth",
    label: "Training & Development",
    path: ROUTES.me.training.trainings,
    icon: "GraduationCap",
    order: 130,
    children: [
      {
        id: "me-training-trainings",
        portal: "me",
        heading: "3. Talent & Growth",
        label: "My Trainings",
        path: ROUTES.me.training.trainings,
        icon: "GraduationCap",
        order: 131,
      },
      {
        id: "me-training-sessions",
        portal: "me",
        heading: "3. Talent & Growth",
        label: "Sessions",
        path: ROUTES.me.training.sessions,
        icon: "Calendar",
        order: 132,
      },
      {
        id: "me-training-programs",
        portal: "me",
        heading: "3. Talent & Growth",
        label: "Programs",
        path: ROUTES.me.training.programs,
        icon: "BookOpen",
        order: 133,
      },
    ],
  },

  // 4. Finance & Assets
  {
    id: "me-payroll",
    portal: "me",
    heading: "4. Finance & Assets",
    label: "Payroll Management",
    path: ROUTES.me.payroll.payslips,
    icon: "Wallet",
    order: 140,
    children: [
      {
        id: "me-payroll-payslips",
        portal: "me",
        heading: "4. Finance & Assets",
        label: "Payslips",
        path: ROUTES.me.payroll.payslips,
        icon: "Receipt",
        order: 141,
      },
      {
        id: "me-payroll-salary",
        portal: "me",
        heading: "4. Finance & Assets",
        label: "My Salary",
        path: ROUTES.me.payroll.salary,
        icon: "DollarSign",
        order: 142,
      },
      {
        id: "me-payroll-tax",
        portal: "me",
        heading: "4. Finance & Assets",
        label: "Tax",
        path: ROUTES.me.payroll.tax,
        icon: "ReceiptTax",
        order: 143,
      },
      {
        id: "me-payroll-reimbursements-loans",
        portal: "me",
        heading: "4. Finance & Assets",
        label: "Reimbursements & Loans",
        path: ROUTES.me.payroll.reimbursementsLoans,
        icon: "CreditCard",
        order: 144,
      },
      {
        id: "me-payroll-statutory-forms",
        portal: "me",
        heading: "4. Finance & Assets",
        label: "PF/ESI & Forms",
        path: ROUTES.me.payroll.statutoryForms,
        icon: "FileSpreadsheet",
        order: 145,
      },
    ],
  },
  {
    id: "me-assets",
    portal: "me",
    heading: "4. Finance & Assets",
    label: "Assets",
    path: ROUTES.me.assets.dashboard,
    icon: "Package",
    order: 150,
    children: [
      {
        id: "me-assets-dashboard",
        portal: "me",
        heading: "4. Finance & Assets",
        label: "Dashboard",
        path: ROUTES.me.assets.dashboard,
        icon: "LayoutDashboard",
        order: 151,
      },
      {
        id: "me-assets-list",
        portal: "me",
        heading: "4. Finance & Assets",
        label: "My Assets",
        path: ROUTES.me.assets.list,
        icon: "Package",
        order: 152,
      },
      {
        id: "me-assets-requests",
        portal: "me",
        heading: "4. Finance & Assets",
        label: "Requests",
        path: ROUTES.me.assets.requests,
        icon: "Send",
        order: 153,
      },
    ],
  },

  // 5. Communication & Content
  {
    id: "me-meetings",
    portal: "me",
    heading: "5. Communication & Content",
    label: "Meetings",
    path: ROUTES.me.meetings.list,
    icon: "Video",
    order: 160,
    children: [
      {
        id: "me-meetings-list",
        portal: "me",
        heading: "5. Communication & Content",
        label: "Meetings",
        path: ROUTES.me.meetings.list,
        icon: "Calendar",
        order: 161,
      },
      {
        id: "me-meetings-action-items",
        portal: "me",
        heading: "5. Communication & Content",
        label: "Action Items",
        path: ROUTES.me.meetings.actionItems,
        icon: "CheckSquare",
        order: 162,
      },
    ],
  },
  {
    id: "me-documents",
    portal: "me",
    heading: "5. Communication & Content",
    label: "Documents & Contracts",
    path: ROUTES.me.documents.list,
    icon: "FileText",
    order: 170,
    children: [
      {
        id: "me-documents-list",
        portal: "me",
        heading: "5. Communication & Content",
        label: "HR Documents",
        path: ROUTES.me.documents.list,
        icon: "FileText",
        order: 171,
      },
      {
        id: "me-documents-contracts",
        portal: "me",
        heading: "5. Communication & Content",
        label: "My Contracts",
        path: ROUTES.me.documents.contracts,
        icon: "FileCheck",
        order: 172,
      },
      {
        id: "me-documents-acknowledgements",
        portal: "me",
        heading: "5. Communication & Content",
        label: "Acknowledgements",
        path: ROUTES.me.documents.acknowledgements,
        icon: "CheckCircle",
        order: 173,
      },
      {
        id: "me-documents-requests",
        portal: "me",
        heading: "5. Communication & Content",
        label: "Document Requests",
        path: ROUTES.me.documents.requests,
        icon: "Send",
        order: 174,
      },
    ],
  },
  {
    id: "me-media",
    portal: "me",
    heading: "5. Communication & Content",
    label: "Media Library",
    path: ROUTES.me.media,
    icon: "Image",
    order: 180,
    children: [
      {
        id: "me-media-shared",
        portal: "me",
        heading: "5. Communication & Content",
        label: "Shared Files",
        path: ROUTES.me.media,
        icon: "Share2",
        order: 181,
      },
      {
        id: "me-media-my-files",
        portal: "me",
        heading: "5. Communication & Content",
        label: "My Files",
        path: ROUTES.me.media,
        icon: "Folder",
        order: 182,
      },
    ],
  },

  // 6. My Account
  {
    id: "me-profile",
    portal: "me",
    heading: "6. My Account",
    label: "My Profile",
    path: ROUTES.me.profile,
    icon: "User",
    order: 190,
  },
  {
    id: "me-helpdesk",
    portal: "me",
    heading: "6. My Account",
    label: "Helpdesk",
    path: ROUTES.me.helpdesk,
    icon: "LifeBuoy",
    order: 200,
  },
  {
    id: "me-account",
    portal: "me",
    heading: "6. My Account",
    label: "Account & Security",
    path: ROUTES.me.account,
    icon: "ShieldCheck",
    order: 210,
  },

  // 7. Manager Only
  {
    id: "me-team",
    portal: "me",
    heading: "7. Manager Only",
    label: "My Team",
    path: ROUTES.me.team,
    icon: "Users2",
    order: 220,
  },
  {
    id: "me-approvals",
    portal: "me",
    heading: "7. Manager Only",
    label: "Approvals",
    path: ROUTES.me.approvals,
    icon: "UserCheck",
    order: 230,
  },
];

// ─────────────────────────────────────────────────────────────
// 3. TENANT SIDEBAR REGISTRY (/tenant/*) — Exact Section 4.3 Order
// ─────────────────────────────────────────────────────────────
export const TENANT_NAVIGATION_REGISTRY: NavRegistryItem[] = [
  // Workspace
  {
    id: "tenant-dashboard",
    portal: "tenant",
    heading: "Workspace",
    label: "Tenant Dashboard",
    path: ROUTES.tenant.dashboard,
    icon: "LayoutDashboard",
    order: 10,
    exactMatch: true,
  },
  {
    id: "tenant-company-profile",
    portal: "tenant",
    heading: "Workspace",
    label: "Company Profile and Billing Address",
    path: ROUTES.tenant.companyProfile,
    icon: "Building2",
    order: 20,
  },
  {
    id: "tenant-users",
    portal: "tenant",
    heading: "Workspace",
    label: "Users",
    path: ROUTES.tenant.users,
    icon: "Users",
    order: 30,
  },
  {
    id: "tenant-roles",
    portal: "tenant",
    heading: "Workspace",
    label: "Roles and Permissions",
    path: ROUTES.tenant.roles,
    icon: "ShieldCheck",
    order: 40,
  },
  {
    id: "tenant-modules",
    portal: "tenant",
    heading: "Workspace",
    label: "Modules and Features",
    path: ROUTES.tenant.modules,
    icon: "Boxes",
    order: 50,
  },

  // Subscription
  {
    id: "tenant-subscription",
    portal: "tenant",
    heading: "Subscription",
    label: "Plan and Usage",
    path: ROUTES.tenant.subscription,
    icon: "CreditCard",
    order: 60,
  },
  {
    id: "tenant-billing",
    portal: "tenant",
    heading: "Subscription",
    label: "Billing and Invoices",
    path: ROUTES.tenant.billing,
    icon: "Receipt",
    order: 70,
  },

  // Configuration
  {
    id: "tenant-branding",
    portal: "tenant",
    heading: "Configuration",
    label: "Branding",
    path: ROUTES.tenant.branding,
    icon: "Sparkles",
    order: 80,
  },
  {
    id: "tenant-settings",
    portal: "tenant",
    heading: "Configuration",
    label: "Settings",
    path: ROUTES.tenant.settings,
    icon: "Settings",
    order: 90,
  },
  {
    id: "tenant-domain",
    portal: "tenant",
    heading: "Configuration",
    label: "Domain",
    path: ROUTES.tenant.domain,
    icon: "Globe",
    order: 100,
  },
  {
    id: "tenant-integrations",
    portal: "tenant",
    heading: "Configuration",
    label: "Integrations",
    path: ROUTES.tenant.integrations,
    icon: "Cpu",
    order: 110,
  },
  {
    id: "tenant-data",
    portal: "tenant",
    heading: "Configuration",
    label: "Data",
    path: ROUTES.tenant.data,
    icon: "Database",
    order: 120,
  },
  {
    id: "tenant-audit-logs",
    portal: "tenant",
    heading: "Configuration",
    label: "Audit Logs",
    path: ROUTES.tenant.auditLogs,
    icon: "FileSearch",
    order: 130,
  },
  {
    id: "tenant-support",
    portal: "tenant",
    heading: "Configuration",
    label: "Support",
    path: ROUTES.tenant.support,
    icon: "HelpCircle",
    order: 140,
  },

  // HR Panel Link (Section 4.3: links directly to /hr/*)
  {
    id: "tenant-hr-panel-group",
    portal: "tenant",
    heading: "HR Panel",
    label: "HR Management Portal",
    path: ROUTES.hr.dashboard,
    icon: "Briefcase",
    order: 200,
  },

  // Employee View Link
  {
    id: "tenant-employee-view",
    portal: "tenant",
    heading: "Employee View",
    label: "My Employee Portal",
    path: ROUTES.me.dashboard,
    icon: "User",
    order: 210,
  },
];

/**
 * Get items filtered for a specific active portal
 */
export function getNavItemsForPortal(
  portal: PortalId,
  context?: NavigationFilterContext
): NavRegistryItem[] {
  switch (portal) {
    case "tenant":
      return TENANT_NAVIGATION_REGISTRY;
    case "hr":
      return HR_NAVIGATION_REGISTRY;
    case "me":
      return EMPLOYEE_NAVIGATION_REGISTRY;
    default:
      return [];
  }
}

/**
 * Checks if a route path is currently active
 */
export function isPathActive(currentPath: string, targetPath: string, exact = false): boolean {
  const normCurrent = currentPath.toLowerCase().replace(/\/+$/, "") || "/";
  const normTarget = targetPath.toLowerCase().replace(/\/+$/, "") || "/";
  if (exact) return normCurrent === normTarget;
  return normCurrent === normTarget || normCurrent.startsWith(`${normTarget}/`);
}
